// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entrasync.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const convertMissingEntraGroupsToLocal = `-- name: ConvertMissingEntraGroupsToLocal :exec
UPDATE groups
SET
  source = 'local',
  updated_at = NOW()
WHERE source = 'entra'
  AND NOT (id = ANY($1::UUID[]))
`

func (q *Queries) ConvertMissingEntraGroupsToLocal(ctx context.Context, groupIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, convertMissingEntraGroupsToLocal, groupIds)
	return err
}

const convertMissingEntraUsersToLocal = `-- name: ConvertMissingEntraUsersToLocal :exec
UPDATE users
SET
  source = 'local',
  updated_at = NOW()
WHERE source = 'entra'
  AND NOT (id = ANY($1::UUID[]))
`

func (q *Queries) ConvertMissingEntraUsersToLocal(ctx context.Context, userIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, convertMissingEntraUsersToLocal, userIds)
	return err
}

const deleteUserMembersForEntraGroups = `-- name: DeleteUserMembersForEntraGroups :exec
DELETE FROM group_memberships AS gm
USING groups AS g
WHERE gm.group_id = g.id
  AND g.source = 'entra'
  AND gm.member_kind = 'user'
`

func (q *Queries) DeleteUserMembersForEntraGroups(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteUserMembersForEntraGroups)
	return err
}
