// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entrasync.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const bulkUpsertSyncedUserMemberships = `-- name: BulkUpsertSyncedUserMemberships :exec
INSERT INTO group_user_memberships (
  group_id,
  user_id,
  origin
)
SELECT
  UNNEST($1::UUID[]),
  UNNEST($2::UUID[]),
  'synced'
ON CONFLICT (group_id, user_id) DO UPDATE
SET
  origin = 'synced',
  updated_at = NOW()
`

type BulkUpsertSyncedUserMembershipsParams struct {
	GroupIds []uuid.UUID
	UserIds  []uuid.UUID
}

func (q *Queries) BulkUpsertSyncedUserMemberships(ctx context.Context, arg BulkUpsertSyncedUserMembershipsParams) error {
	_, err := q.db.Exec(ctx, bulkUpsertSyncedUserMemberships, arg.GroupIds, arg.UserIds)
	return err
}

const convertMissingEntraGroupsToLocal = `-- name: ConvertMissingEntraGroupsToLocal :exec
UPDATE groups
SET
  source = 'local',
  updated_at = NOW()
WHERE source = 'entra'
  AND id <> ALL($1::UUID[])
`

func (q *Queries) ConvertMissingEntraGroupsToLocal(ctx context.Context, groupIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, convertMissingEntraGroupsToLocal, groupIds)
	return err
}

const convertMissingEntraUsersToLocal = `-- name: ConvertMissingEntraUsersToLocal :exec
UPDATE users
SET
  source = 'local',
  updated_at = NOW()
WHERE source = 'entra'
  AND id <> ALL($1::UUID[])
`

func (q *Queries) ConvertMissingEntraUsersToLocal(ctx context.Context, userIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, convertMissingEntraUsersToLocal, userIds)
	return err
}

const deleteUserMembersForEntraGroups = `-- name: DeleteUserMembersForEntraGroups :exec
DELETE FROM group_user_memberships AS gum
USING groups AS g
WHERE g.id = gum.group_id
  AND g.source = 'entra'
`

func (q *Queries) DeleteUserMembersForEntraGroups(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteUserMembersForEntraGroups)
	return err
}
