// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: executables.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const getExecutable = `-- name: GetExecutable :one
SELECT
  e.id,
  e.file_sha256,
  e.file_name,
  e.file_bundle_id,
  e.file_bundle_path,
  e.signing_id,
  e.team_id,
  e.cdhash,
  COALESCE(event_counts.occurrences, 0)::INT4 AS occurrences,
  e.entitlements,
  e.signing_chain,
  e.created_at
FROM executables AS e
LEFT JOIN (
  SELECT
    executable_id,
    COUNT(*)::INT4 AS occurrences
  FROM execution_events
  GROUP BY executable_id
) AS event_counts
  ON event_counts.executable_id = e.id
WHERE e.id = $1
`

type GetExecutableRow struct {
	ID             uuid.UUID
	FileSHA256     string
	FileName       string
	FileBundleID   string
	FileBundlePath string
	SigningID      string
	TeamID         string
	Cdhash         string
	Occurrences    int32
	Entitlements   []byte
	SigningChain   []byte
	CreatedAt      time.Time
}

func (q *Queries) GetExecutable(ctx context.Context, id uuid.UUID) (GetExecutableRow, error) {
	row := q.db.QueryRow(ctx, getExecutable, id)
	var i GetExecutableRow
	err := row.Scan(
		&i.ID,
		&i.FileSHA256,
		&i.FileName,
		&i.FileBundleID,
		&i.FileBundlePath,
		&i.SigningID,
		&i.TeamID,
		&i.Cdhash,
		&i.Occurrences,
		&i.Entitlements,
		&i.SigningChain,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateExecutable = `-- name: GetOrCreateExecutable :one
INSERT INTO executables (
  file_sha256,
  file_name,
  file_bundle_id,
  file_bundle_path,
  signing_id,
  team_id,
  cdhash,
  entitlements,
  signing_chain
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
ON CONFLICT (file_sha256, file_name) DO UPDATE
SET file_name = executables.file_name
RETURNING
  id,
  file_sha256,
  file_name,
  file_bundle_id,
  file_bundle_path,
  signing_id,
  team_id,
  cdhash,
  entitlements,
  signing_chain,
  created_at
`

type GetOrCreateExecutableParams struct {
	FileSHA256     string
	FileName       string
	FileBundleID   string
	FileBundlePath string
	SigningID      string
	TeamID         string
	Cdhash         string
	Entitlements   []byte
	SigningChain   []byte
}

func (q *Queries) GetOrCreateExecutable(ctx context.Context, arg GetOrCreateExecutableParams) (Executable, error) {
	row := q.db.QueryRow(ctx, getOrCreateExecutable,
		arg.FileSHA256,
		arg.FileName,
		arg.FileBundleID,
		arg.FileBundlePath,
		arg.SigningID,
		arg.TeamID,
		arg.Cdhash,
		arg.Entitlements,
		arg.SigningChain,
	)
	var i Executable
	err := row.Scan(
		&i.ID,
		&i.FileSHA256,
		&i.FileName,
		&i.FileBundleID,
		&i.FileBundlePath,
		&i.SigningID,
		&i.TeamID,
		&i.Cdhash,
		&i.Entitlements,
		&i.SigningChain,
		&i.CreatedAt,
	)
	return i, err
}
