// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: executables.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const getExecutable = `-- name: GetExecutable :one
SELECT
  id,
  file_sha256,
  file_name,
  file_bundle_id,
  file_bundle_path,
  signing_id,
  team_id,
  cdhash,
  entitlements,
  signing_chain,
  created_at
FROM executables
WHERE id = $1
`

func (q *Queries) GetExecutable(ctx context.Context, id uuid.UUID) (Executable, error) {
	row := q.db.QueryRow(ctx, getExecutable, id)
	var i Executable
	err := row.Scan(
		&i.ID,
		&i.FileSHA256,
		&i.FileName,
		&i.FileBundleID,
		&i.FileBundlePath,
		&i.SigningID,
		&i.TeamID,
		&i.Cdhash,
		&i.Entitlements,
		&i.SigningChain,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateExecutable = `-- name: GetOrCreateExecutable :one
WITH inserted AS (
  INSERT INTO executables (
    file_sha256,
    file_name,
    file_bundle_id,
    file_bundle_path,
    signing_id,
    team_id,
    cdhash,
    entitlements,
    signing_chain
  )
  VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
  )
  ON CONFLICT (file_sha256, file_name) DO NOTHING
  RETURNING
    id,
    file_sha256,
    file_name,
    file_bundle_id,
    file_bundle_path,
    signing_id,
    team_id,
    cdhash,
    entitlements,
    signing_chain,
    created_at
)
SELECT id, file_sha256, file_name, file_bundle_id, file_bundle_path, signing_id, team_id, cdhash, entitlements, signing_chain, created_at FROM inserted
UNION ALL
SELECT
  id,
  file_sha256,
  file_name,
  file_bundle_id,
  file_bundle_path,
  signing_id,
  team_id,
  cdhash,
  entitlements,
  signing_chain,
  created_at
FROM executables
WHERE file_sha256 = $1
  AND file_name = $2
  AND NOT EXISTS (SELECT 1 FROM inserted)
LIMIT 1
`

type GetOrCreateExecutableParams struct {
	FileSHA256     string
	FileName       string
	FileBundleID   string
	FileBundlePath string
	SigningID      string
	TeamID         string
	Cdhash         string
	Entitlements   []byte
	SigningChain   []byte
}

type GetOrCreateExecutableRow struct {
	ID             uuid.UUID
	FileSHA256     string
	FileName       string
	FileBundleID   string
	FileBundlePath string
	SigningID      string
	TeamID         string
	Cdhash         string
	Entitlements   []byte
	SigningChain   []byte
	CreatedAt      time.Time
}

func (q *Queries) GetOrCreateExecutable(ctx context.Context, arg GetOrCreateExecutableParams) (GetOrCreateExecutableRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateExecutable,
		arg.FileSHA256,
		arg.FileName,
		arg.FileBundleID,
		arg.FileBundlePath,
		arg.SigningID,
		arg.TeamID,
		arg.Cdhash,
		arg.Entitlements,
		arg.SigningChain,
	)
	var i GetOrCreateExecutableRow
	err := row.Scan(
		&i.ID,
		&i.FileSHA256,
		&i.FileName,
		&i.FileBundleID,
		&i.FileBundlePath,
		&i.SigningID,
		&i.TeamID,
		&i.Cdhash,
		&i.Entitlements,
		&i.SigningChain,
		&i.CreatedAt,
	)
	return i, err
}
