// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_events.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createExecutionEvent = `-- name: CreateExecutionEvent :one
INSERT INTO execution_events (
  machine_id,
  executable_id,
  decision,
  file_path,
  executing_user,
  logged_in_users,
  current_sessions,
  occurred_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING
  id,
  machine_id,
  executable_id,
  decision,
  file_path,
  executing_user,
  logged_in_users,
  current_sessions,
  occurred_at,
  created_at
`

type CreateExecutionEventParams struct {
	MachineID       uuid.UUID
	ExecutableID    uuid.UUID
	Decision        ExecutionDecision
	FilePath        string
	ExecutingUser   string
	LoggedInUsers   []string
	CurrentSessions []string
	OccurredAt      *time.Time
}

func (q *Queries) CreateExecutionEvent(ctx context.Context, arg CreateExecutionEventParams) (ExecutionEvent, error) {
	row := q.db.QueryRow(ctx, createExecutionEvent,
		arg.MachineID,
		arg.ExecutableID,
		arg.Decision,
		arg.FilePath,
		arg.ExecutingUser,
		arg.LoggedInUsers,
		arg.CurrentSessions,
		arg.OccurredAt,
	)
	var i ExecutionEvent
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.ExecutableID,
		&i.Decision,
		&i.FilePath,
		&i.ExecutingUser,
		&i.LoggedInUsers,
		&i.CurrentSessions,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExecutionEvent = `-- name: DeleteExecutionEvent :exec
DELETE FROM execution_events
WHERE id = $1
`

func (q *Queries) DeleteExecutionEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExecutionEvent, id)
	return err
}

const deleteExecutionEventsBefore = `-- name: DeleteExecutionEventsBefore :execrows
DELETE FROM execution_events
WHERE created_at < $1
`

func (q *Queries) DeleteExecutionEventsBefore(ctx context.Context, beforeCreatedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExecutionEventsBefore, beforeCreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExecutionEvent = `-- name: GetExecutionEvent :one
SELECT
  ee.id,
  ee.machine_id,
  ee.executable_id,
  ee.decision,
  ee.file_path,
  x.file_name,
  x.file_sha256,
  x.file_bundle_id,
  x.file_bundle_path,
  x.signing_id,
  x.team_id,
  x.cdhash,
  ee.executing_user,
  ee.logged_in_users,
  ee.current_sessions,
  x.signing_chain,
  x.entitlements,
  ee.occurred_at,
  ee.created_at
FROM execution_events AS ee
JOIN executables AS x
  ON x.id = ee.executable_id
WHERE ee.id = $1
`

type GetExecutionEventRow struct {
	ID              uuid.UUID
	MachineID       uuid.UUID
	ExecutableID    uuid.UUID
	Decision        ExecutionDecision
	FilePath        string
	FileName        string
	FileSHA256      string
	FileBundleID    string
	FileBundlePath  string
	SigningID       string
	TeamID          string
	Cdhash          string
	ExecutingUser   string
	LoggedInUsers   []string
	CurrentSessions []string
	SigningChain    []byte
	Entitlements    []byte
	OccurredAt      *time.Time
	CreatedAt       time.Time
}

func (q *Queries) GetExecutionEvent(ctx context.Context, id uuid.UUID) (GetExecutionEventRow, error) {
	row := q.db.QueryRow(ctx, getExecutionEvent, id)
	var i GetExecutionEventRow
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.ExecutableID,
		&i.Decision,
		&i.FilePath,
		&i.FileName,
		&i.FileSHA256,
		&i.FileBundleID,
		&i.FileBundlePath,
		&i.SigningID,
		&i.TeamID,
		&i.Cdhash,
		&i.ExecutingUser,
		&i.LoggedInUsers,
		&i.CurrentSessions,
		&i.SigningChain,
		&i.Entitlements,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}
