// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_access_events.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createFileAccessEvent = `-- name: CreateFileAccessEvent :one
INSERT INTO file_access_events (
  id,
  machine_id,
  executable_id,
  rule_version,
  rule_name,
  target,
  decision,
  process_chain,
  occurred_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
RETURNING
  id,
  machine_id,
  executable_id,
  rule_version,
  rule_name,
  target,
  decision,
  process_chain,
  occurred_at,
  created_at
`

type CreateFileAccessEventParams struct {
	ID           uuid.UUID
	MachineID    uuid.UUID
	ExecutableID *uuid.UUID
	RuleVersion  string
	RuleName     string
	Target       string
	Decision     string
	ProcessChain []byte
	OccurredAt   *time.Time
}

func (q *Queries) CreateFileAccessEvent(ctx context.Context, arg CreateFileAccessEventParams) (FileAccessEvent, error) {
	row := q.db.QueryRow(ctx, createFileAccessEvent,
		arg.ID,
		arg.MachineID,
		arg.ExecutableID,
		arg.RuleVersion,
		arg.RuleName,
		arg.Target,
		arg.Decision,
		arg.ProcessChain,
		arg.OccurredAt,
	)
	var i FileAccessEvent
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.ExecutableID,
		&i.RuleVersion,
		&i.RuleName,
		&i.Target,
		&i.Decision,
		&i.ProcessChain,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFileAccessEvent = `-- name: DeleteFileAccessEvent :exec
DELETE FROM file_access_events
WHERE id = $1
`

func (q *Queries) DeleteFileAccessEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileAccessEvent, id)
	return err
}

const deleteFileAccessEventsBefore = `-- name: DeleteFileAccessEventsBefore :execrows
DELETE FROM file_access_events
WHERE created_at < $1
`

func (q *Queries) DeleteFileAccessEventsBefore(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFileAccessEventsBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFileAccessEvent = `-- name: GetFileAccessEvent :one
SELECT
  fe.id,
  fe.machine_id,
  fe.executable_id,
  fe.rule_version,
  fe.rule_name,
  fe.target,
  fe.decision,
  COALESCE(x.file_name, '') AS file_name,
  COALESCE(x.file_sha256, '') AS file_sha256,
  COALESCE(x.signing_id, '') AS signing_id,
  COALESCE(x.team_id, '') AS team_id,
  COALESCE(x.cdhash, '') AS cdhash,
  fe.process_chain,
  fe.occurred_at,
  fe.created_at
FROM file_access_events AS fe
LEFT JOIN executables AS x ON x.id = fe.executable_id
WHERE fe.id = $1
`

type GetFileAccessEventRow struct {
	ID           uuid.UUID
	MachineID    uuid.UUID
	ExecutableID *uuid.UUID
	RuleVersion  string
	RuleName     string
	Target       string
	Decision     string
	FileName     string
	FileSha256   string
	SigningID    string
	TeamID       string
	Cdhash       string
	ProcessChain []byte
	OccurredAt   *time.Time
	CreatedAt    time.Time
}

func (q *Queries) GetFileAccessEvent(ctx context.Context, id uuid.UUID) (GetFileAccessEventRow, error) {
	row := q.db.QueryRow(ctx, getFileAccessEvent, id)
	var i GetFileAccessEventRow
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.ExecutableID,
		&i.RuleVersion,
		&i.RuleName,
		&i.Target,
		&i.Decision,
		&i.FileName,
		&i.FileSha256,
		&i.SigningID,
		&i.TeamID,
		&i.Cdhash,
		&i.ProcessChain,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}
