// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_access_events.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createFileAccessEvent = `-- name: CreateFileAccessEvent :one
INSERT INTO file_access_events (
  machine_id,
  rule_version,
  rule_name,
  target,
  decision,
  process_chain,
  occurred_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING
  id,
  machine_id,
  rule_version,
  rule_name,
  target,
  decision,
  process_chain,
  occurred_at,
  created_at
`

type CreateFileAccessEventParams struct {
	MachineID    uuid.UUID
	RuleVersion  string
	RuleName     string
	Target       string
	Decision     FileAccessDecision
	ProcessChain []byte
	OccurredAt   *time.Time
}

func (q *Queries) CreateFileAccessEvent(ctx context.Context, arg CreateFileAccessEventParams) (FileAccessEvent, error) {
	row := q.db.QueryRow(ctx, createFileAccessEvent,
		arg.MachineID,
		arg.RuleVersion,
		arg.RuleName,
		arg.Target,
		arg.Decision,
		arg.ProcessChain,
		arg.OccurredAt,
	)
	var i FileAccessEvent
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.RuleVersion,
		&i.RuleName,
		&i.Target,
		&i.Decision,
		&i.ProcessChain,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFileAccessEvent = `-- name: DeleteFileAccessEvent :exec
DELETE FROM file_access_events
WHERE id = $1
`

func (q *Queries) DeleteFileAccessEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileAccessEvent, id)
	return err
}

const deleteFileAccessEventsBefore = `-- name: DeleteFileAccessEventsBefore :execrows
DELETE FROM file_access_events
WHERE created_at < $1
`

func (q *Queries) DeleteFileAccessEventsBefore(ctx context.Context, beforeCreatedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFileAccessEventsBefore, beforeCreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFileAccessEvent = `-- name: GetFileAccessEvent :one
SELECT
  id,
  machine_id,
  rule_version,
  rule_name,
  target,
  decision,
  process_chain,
  occurred_at,
  created_at
FROM file_access_events
WHERE id = $1
`

func (q *Queries) GetFileAccessEvent(ctx context.Context, id uuid.UUID) (FileAccessEvent, error) {
	row := q.db.QueryRow(ctx, getFileAccessEvent, id)
	var i FileAccessEvent
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.RuleVersion,
		&i.RuleName,
		&i.Target,
		&i.Decision,
		&i.ProcessChain,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}
