// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGroup = `-- name: DeleteGroup :one
WITH matched AS (
  SELECT g.source
  FROM groups AS g
  WHERE g.id = $1
),
deleted AS (
  DELETE FROM groups AS g
  WHERE g.id = $1
    AND g.source = 'local'
  RETURNING 1
)
SELECT
  CASE
    WHEN EXISTS (SELECT 1 FROM deleted) THEN 'deleted'
    WHEN EXISTS (SELECT 1 FROM matched WHERE source <> 'local') THEN 'read_only'
    ELSE 'not_found'
  END AS status
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, deleteGroup, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getGroup = `-- name: GetGroup :one
SELECT
  g.id,
  g.name,
  g.description,
  g.source,
  (
    SELECT COUNT(*)::INT4
    FROM group_memberships AS gm
    WHERE gm.group_id = g.id
  ) AS member_count,
  g.created_at,
  g.updated_at
FROM groups AS g
WHERE g.id = $1
`

type GetGroupRow struct {
	ID          uuid.UUID
	Name        string
	Description string
	Source      PrincipalSource
	MemberCount int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (GetGroupRow, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i GetGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Source,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroups = `-- name: ListGroups :many
SELECT
  id,
  name,
  description,
  source,
  created_at,
  updated_at
FROM groups
ORDER BY name ASC, id ASC
LIMIT $2
OFFSET $1
`

type ListGroupsParams struct {
	OffsetCount int32
	LimitCount  int32
}

func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
WITH matched AS (
  SELECT g.source
  FROM groups AS g
  WHERE g.id = $1
),
updated AS (
  UPDATE groups AS g
  SET
    name = $2,
    description = $3,
    updated_at = NOW()
  WHERE g.id = $1
    AND g.source = 'local'
  RETURNING
    g.id,
    g.name,
    g.description,
    g.source,
    (
      SELECT COUNT(*)::INT4
      FROM group_memberships AS gm
      WHERE gm.group_id = g.id
    ) AS member_count,
    g.created_at,
    g.updated_at
)
SELECT
  CASE
    WHEN EXISTS (SELECT 1 FROM updated) THEN 'updated'
    WHEN EXISTS (SELECT 1 FROM matched WHERE source <> 'local') THEN 'read_only'
    ELSE 'not_found'
  END AS status,
  u.id,
  u.name,
  u.description,
  u.source,
  COALESCE(u.member_count, 0)::INT4 AS member_count,
  u.created_at,
  u.updated_at
FROM (VALUES (1)) AS marker(dummy)
LEFT JOIN updated AS u
  ON TRUE
`

type UpdateGroupParams struct {
	ID          uuid.UUID
	Name        string
	Description string
}

type UpdateGroupRow struct {
	Status      string
	ID          *uuid.UUID
	Name        pgtype.Text
	Description pgtype.Text
	Source      NullPrincipalSource
	MemberCount int32
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (UpdateGroupRow, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.ID, arg.Name, arg.Description)
	var i UpdateGroupRow
	err := row.Scan(
		&i.Status,
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Source,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGroup = `-- name: UpsertGroup :one
INSERT INTO groups (
  id,
  name,
  description,
  source
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
ON CONFLICT (id) DO UPDATE
SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  source = EXCLUDED.source,
  updated_at = NOW()
RETURNING
  id,
  name,
  description,
  source,
  0::INT4 AS member_count,
  created_at,
  updated_at
`

type UpsertGroupParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	Source      PrincipalSource
}

type UpsertGroupRow struct {
	ID          uuid.UUID
	Name        string
	Description string
	Source      PrincipalSource
	MemberCount int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpsertGroup(ctx context.Context, arg UpsertGroupParams) (UpsertGroupRow, error) {
	row := q.db.QueryRow(ctx, upsertGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Source,
	)
	var i UpsertGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Source,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
