// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: machines.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const deleteMachine = `-- name: DeleteMachine :exec
DELETE FROM machines
WHERE id = $1
`

func (q *Queries) DeleteMachine(ctx context.Context, machineID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMachine, machineID)
	return err
}

const getMachine = `-- name: GetMachine :one
SELECT
  m.id,
  m.serial_number,
  m.hostname,
  m.model_identifier,
  m.os_version,
  m.os_build,
  m.santa_version,
  m.primary_user,
  m.primary_user_groups,
  machine_rule_sync_status(
    ms.pending_preflight_at,
    ms.desired_targets,
    ms.applied_targets,
    ms.desired_binary_rule_count,
    ms.binary_rule_count,
    ms.desired_certificate_rule_count,
    ms.certificate_rule_count,
    ms.desired_teamid_rule_count,
    ms.teamid_rule_count,
    ms.desired_signingid_rule_count,
    ms.signingid_rule_count,
    ms.desired_cdhash_rule_count,
    ms.cdhash_rule_count,
    ms.last_clean_sync_at,
    ms.last_reported_counts_match_at
  ) AS rule_sync_status,
  m.client_mode,
  COALESCE(ms.binary_rule_count, 0)::INT4 AS binary_rule_count,
  COALESCE(ms.certificate_rule_count, 0)::INT4 AS certificate_rule_count,
  COALESCE(ms.teamid_rule_count, 0)::INT4 AS teamid_rule_count,
  COALESCE(ms.signingid_rule_count, 0)::INT4 AS signingid_rule_count,
  COALESCE(ms.cdhash_rule_count, 0)::INT4 AS cdhash_rule_count,
  m.last_seen_at,
  m.created_at,
  m.updated_at,
  u.id AS primary_user_id
FROM machines AS m
LEFT JOIN machine_sync_states AS ms
  ON ms.machine_id = m.id
LEFT JOIN users AS u
  ON u.upn = NULLIF(m.primary_user, '')
WHERE m.id = $1
`

type GetMachineRow struct {
	ID                   uuid.UUID
	SerialNumber         string
	Hostname             string
	ModelIdentifier      string
	OsVersion            string
	OsBuild              string
	SantaVersion         string
	PrimaryUser          string
	PrimaryUserGroups    []string
	RuleSyncStatus       string
	ClientMode           SantaClientMode
	BinaryRuleCount      int32
	CertificateRuleCount int32
	TeamIDRuleCount      int32
	SigningIDRuleCount   int32
	CDHashRuleCount      int32
	LastSeenAt           time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	PrimaryUserID        *uuid.UUID
}

func (q *Queries) GetMachine(ctx context.Context, machineID uuid.UUID) (GetMachineRow, error) {
	row := q.db.QueryRow(ctx, getMachine, machineID)
	var i GetMachineRow
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.Hostname,
		&i.ModelIdentifier,
		&i.OsVersion,
		&i.OsBuild,
		&i.SantaVersion,
		&i.PrimaryUser,
		&i.PrimaryUserGroups,
		&i.RuleSyncStatus,
		&i.ClientMode,
		&i.BinaryRuleCount,
		&i.CertificateRuleCount,
		&i.TeamIDRuleCount,
		&i.SigningIDRuleCount,
		&i.CDHashRuleCount,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryUserID,
	)
	return i, err
}

const listMachineIDs = `-- name: ListMachineIDs :many
SELECT id
FROM machines
ORDER BY id ASC
`

func (q *Queries) ListMachineIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMachineIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachineIDsByPrimaryUserID = `-- name: ListMachineIDsByPrimaryUserID :many
SELECT m.id
FROM machines AS m
JOIN users AS u
  ON u.upn = NULLIF(m.primary_user, '')
WHERE u.id = $1
ORDER BY m.id ASC
`

func (q *Queries) ListMachineIDsByPrimaryUserID(ctx context.Context, primaryUserID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMachineIDsByPrimaryUserID, primaryUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachines = `-- name: ListMachines :many
SELECT
  m.id,
  m.serial_number,
  m.hostname,
  m.model_identifier,
  m.os_version,
  m.os_build,
  m.santa_version,
  m.primary_user,
  m.primary_user_groups,
  m.last_seen_at,
  m.created_at,
  m.updated_at,
  u.id AS primary_user_id
FROM machines AS m
LEFT JOIN users AS u
  ON u.upn = NULLIF(m.primary_user, '')
ORDER BY m.last_seen_at DESC
LIMIT $2
OFFSET $1
`

type ListMachinesParams struct {
	OffsetCount int32
	LimitCount  int32
}

type ListMachinesRow struct {
	ID                uuid.UUID
	SerialNumber      string
	Hostname          string
	ModelIdentifier   string
	OsVersion         string
	OsBuild           string
	SantaVersion      string
	PrimaryUser       string
	PrimaryUserGroups []string
	LastSeenAt        time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	PrimaryUserID     *uuid.UUID
}

func (q *Queries) ListMachines(ctx context.Context, arg ListMachinesParams) ([]ListMachinesRow, error) {
	rows, err := q.db.Query(ctx, listMachines, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMachinesRow
	for rows.Next() {
		var i ListMachinesRow
		if err := rows.Scan(
			&i.ID,
			&i.SerialNumber,
			&i.Hostname,
			&i.ModelIdentifier,
			&i.OsVersion,
			&i.OsBuild,
			&i.SantaVersion,
			&i.PrimaryUser,
			&i.PrimaryUserGroups,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMachine = `-- name: UpsertMachine :one
INSERT INTO machines (
  id,
  serial_number,
  hostname,
  model_identifier,
  os_version,
  os_build,
  santa_version,
  primary_user,
  primary_user_groups,
  client_mode,
  last_seen_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
)
ON CONFLICT (id) DO UPDATE
SET
  serial_number = EXCLUDED.serial_number,
  hostname = EXCLUDED.hostname,
  model_identifier = EXCLUDED.model_identifier,
  os_version = EXCLUDED.os_version,
  os_build = EXCLUDED.os_build,
  santa_version = EXCLUDED.santa_version,
  primary_user = EXCLUDED.primary_user,
  primary_user_groups = EXCLUDED.primary_user_groups,
  client_mode = EXCLUDED.client_mode,
  last_seen_at = EXCLUDED.last_seen_at,
  updated_at = NOW()
RETURNING
  id,
  serial_number,
  hostname,
  model_identifier,
  os_version,
  os_build,
  santa_version,
  primary_user,
  primary_user_groups,
  client_mode,
  last_seen_at,
  created_at,
  updated_at
`

type UpsertMachineParams struct {
	MachineID         uuid.UUID
	SerialNumber      string
	Hostname          string
	ModelIdentifier   string
	OsVersion         string
	OsBuild           string
	SantaVersion      string
	PrimaryUser       string
	PrimaryUserGroups []string
	ClientMode        SantaClientMode
	LastSeenAt        time.Time
}

func (q *Queries) UpsertMachine(ctx context.Context, arg UpsertMachineParams) (Machine, error) {
	row := q.db.QueryRow(ctx, upsertMachine,
		arg.MachineID,
		arg.SerialNumber,
		arg.Hostname,
		arg.ModelIdentifier,
		arg.OsVersion,
		arg.OsBuild,
		arg.SantaVersion,
		arg.PrimaryUser,
		arg.PrimaryUserGroups,
		arg.ClientMode,
		arg.LastSeenAt,
	)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.SerialNumber,
		&i.Hostname,
		&i.ModelIdentifier,
		&i.OsVersion,
		&i.OsBuild,
		&i.SantaVersion,
		&i.PrimaryUser,
		&i.PrimaryUserGroups,
		&i.ClientMode,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
