// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: machines.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMachine = `-- name: DeleteMachine :exec
DELETE FROM machines
WHERE machine_id = $1
`

func (q *Queries) DeleteMachine(ctx context.Context, machineID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMachine, machineID)
	return err
}

const getMachine = `-- name: GetMachine :one
SELECT
  m.machine_id,
  m.serial_number,
  m.hostname,
  m.model_identifier,
  m.os_version,
  m.os_build,
  m.santa_version,
  m.primary_user,
  m.primary_user_groups_raw,
  COALESCE(rs.request_clean_sync, FALSE) AS request_clean_sync,
  m.last_seen_at,
  m.created_at,
  m.updated_at,
  u.id AS primary_user_id
FROM machines AS m
LEFT JOIN machine_rule_sync_states AS rs
  ON rs.machine_id = m.machine_id
LEFT JOIN users AS u
  ON u.upn = m.primary_user
  AND m.primary_user <> ''
WHERE m.machine_id = $1
`

type GetMachineRow struct {
	MachineID            uuid.UUID
	SerialNumber         string
	Hostname             string
	ModelIdentifier      string
	OsVersion            string
	OsBuild              string
	SantaVersion         string
	PrimaryUser          string
	PrimaryUserGroupsRaw []byte
	RequestCleanSync     bool
	LastSeenAt           time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	PrimaryUserID        pgtype.UUID
}

func (q *Queries) GetMachine(ctx context.Context, machineID uuid.UUID) (GetMachineRow, error) {
	row := q.db.QueryRow(ctx, getMachine, machineID)
	var i GetMachineRow
	err := row.Scan(
		&i.MachineID,
		&i.SerialNumber,
		&i.Hostname,
		&i.ModelIdentifier,
		&i.OsVersion,
		&i.OsBuild,
		&i.SantaVersion,
		&i.PrimaryUser,
		&i.PrimaryUserGroupsRaw,
		&i.RequestCleanSync,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrimaryUserID,
	)
	return i, err
}

const listMachines = `-- name: ListMachines :many
SELECT
  m.machine_id,
  m.serial_number,
  m.hostname,
  m.model_identifier,
  m.os_version,
  m.os_build,
  m.santa_version,
  m.primary_user,
  m.primary_user_groups_raw,
  m.last_seen_at,
  m.created_at,
  m.updated_at,
  u.id AS primary_user_id
FROM machines AS m
LEFT JOIN users AS u
  ON u.upn = m.primary_user
  AND m.primary_user <> ''
ORDER BY m.last_seen_at DESC
LIMIT $1
OFFSET $2
`

type ListMachinesParams struct {
	Limit  int32
	Offset int32
}

type ListMachinesRow struct {
	MachineID            uuid.UUID
	SerialNumber         string
	Hostname             string
	ModelIdentifier      string
	OsVersion            string
	OsBuild              string
	SantaVersion         string
	PrimaryUser          string
	PrimaryUserGroupsRaw []byte
	LastSeenAt           time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	PrimaryUserID        pgtype.UUID
}

func (q *Queries) ListMachines(ctx context.Context, arg ListMachinesParams) ([]ListMachinesRow, error) {
	rows, err := q.db.Query(ctx, listMachines, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMachinesRow
	for rows.Next() {
		var i ListMachinesRow
		if err := rows.Scan(
			&i.MachineID,
			&i.SerialNumber,
			&i.Hostname,
			&i.ModelIdentifier,
			&i.OsVersion,
			&i.OsBuild,
			&i.SantaVersion,
			&i.PrimaryUser,
			&i.PrimaryUserGroupsRaw,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrimaryUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMachine = `-- name: UpsertMachine :one
INSERT INTO machines (
  machine_id,
  serial_number,
  hostname,
  model_identifier,
  os_version,
  os_build,
  santa_version,
  primary_user,
  primary_user_groups_raw,
  last_seen_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
ON CONFLICT (machine_id) DO UPDATE SET
  serial_number = EXCLUDED.serial_number,
  hostname = EXCLUDED.hostname,
  model_identifier = EXCLUDED.model_identifier,
  os_version = EXCLUDED.os_version,
  os_build = EXCLUDED.os_build,
  santa_version = EXCLUDED.santa_version,
  primary_user = EXCLUDED.primary_user,
  primary_user_groups_raw = EXCLUDED.primary_user_groups_raw,
  last_seen_at = EXCLUDED.last_seen_at,
  updated_at = NOW()
RETURNING
  machine_id,
  serial_number,
  hostname,
  model_identifier,
  os_version,
  os_build,
  santa_version,
  primary_user,
  primary_user_groups_raw,
  last_seen_at,
  created_at,
  updated_at
`

type UpsertMachineParams struct {
	MachineID            uuid.UUID
	SerialNumber         string
	Hostname             string
	ModelIdentifier      string
	OsVersion            string
	OsBuild              string
	SantaVersion         string
	PrimaryUser          string
	PrimaryUserGroupsRaw []byte
	LastSeenAt           time.Time
}

func (q *Queries) UpsertMachine(ctx context.Context, arg UpsertMachineParams) (Machine, error) {
	row := q.db.QueryRow(ctx, upsertMachine,
		arg.MachineID,
		arg.SerialNumber,
		arg.Hostname,
		arg.ModelIdentifier,
		arg.OsVersion,
		arg.OsBuild,
		arg.SantaVersion,
		arg.PrimaryUser,
		arg.PrimaryUserGroupsRaw,
		arg.LastSeenAt,
	)
	var i Machine
	err := row.Scan(
		&i.MachineID,
		&i.SerialNumber,
		&i.Hostname,
		&i.ModelIdentifier,
		&i.OsVersion,
		&i.OsBuild,
		&i.SantaVersion,
		&i.PrimaryUser,
		&i.PrimaryUserGroupsRaw,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
