// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const addSyncedUserMembership = `-- name: AddSyncedUserMembership :exec
INSERT INTO group_user_memberships (
  id,
  group_id,
  user_id,
  origin
)
VALUES (
  $1,
  $2,
  $3,
  'synced'
)
ON CONFLICT (group_id, user_id) DO UPDATE
SET
  origin = 'synced'
`

type AddSyncedUserMembershipParams struct {
	ID      uuid.UUID
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) AddSyncedUserMembership(ctx context.Context, arg AddSyncedUserMembershipParams) error {
	_, err := q.db.Exec(ctx, addSyncedUserMembership, arg.ID, arg.GroupID, arg.UserID)
	return err
}

const createMachineMembership = `-- name: CreateMachineMembership :one
INSERT INTO group_machine_memberships (
  id,
  group_id,
  machine_id,
  origin
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING
  id,
  group_id,
  machine_id,
  origin,
  created_at,
  updated_at
`

type CreateMachineMembershipParams struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	MachineID uuid.UUID
	Origin    MembershipOrigin
}

func (q *Queries) CreateMachineMembership(ctx context.Context, arg CreateMachineMembershipParams) (GroupMachineMembership, error) {
	row := q.db.QueryRow(ctx, createMachineMembership,
		arg.ID,
		arg.GroupID,
		arg.MachineID,
		arg.Origin,
	)
	var i GroupMachineMembership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.MachineID,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserMembership = `-- name: CreateUserMembership :one
INSERT INTO group_user_memberships (
  id,
  group_id,
  user_id,
  origin
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING
  id,
  group_id,
  user_id,
  origin,
  created_at,
  updated_at
`

type CreateUserMembershipParams struct {
	ID      uuid.UUID
	GroupID uuid.UUID
	UserID  uuid.UUID
	Origin  MembershipOrigin
}

func (q *Queries) CreateUserMembership(ctx context.Context, arg CreateUserMembershipParams) (GroupUserMembership, error) {
	row := q.db.QueryRow(ctx, createUserMembership,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.Origin,
	)
	var i GroupUserMembership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMachineMembership = `-- name: DeleteMachineMembership :execrows
DELETE FROM group_machine_memberships
WHERE id = $1
`

func (q *Queries) DeleteMachineMembership(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMachineMembership, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserMembership = `-- name: DeleteUserMembership :execrows
DELETE FROM group_user_memberships
WHERE id = $1
`

func (q *Queries) DeleteUserMembership(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserMembership, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPersistedMembershipView = `-- name: GetPersistedMembershipView :one
SELECT
  gm.id,
  g.id AS group_id,
  g.name AS group_name,
  g.source AS group_source,
  gm.member_kind,
  gm.member_id,
  COALESCE(
    CASE
      WHEN gm.member_kind = 'user' THEN NULLIF(u.display_name, '')
      ELSE NULLIF(m.hostname, '')
    END,
    ''
  )::TEXT AS member_name,
  gm.created_at,
  gm.updated_at
FROM group_memberships AS gm
JOIN groups AS g
  ON g.id = gm.group_id
LEFT JOIN users AS u
  ON gm.member_kind = 'user'
  AND u.id = gm.member_id
LEFT JOIN machines AS m
  ON gm.member_kind = 'machine'
  AND m.id = gm.member_id
WHERE gm.id = $1
`

type GetPersistedMembershipViewRow struct {
	ID          uuid.UUID
	GroupID     uuid.UUID
	GroupName   string
	GroupSource PrincipalSource
	MemberKind  MembershipMemberKind
	MemberID    uuid.UUID
	MemberName  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetPersistedMembershipView(ctx context.Context, id uuid.UUID) (GetPersistedMembershipViewRow, error) {
	row := q.db.QueryRow(ctx, getPersistedMembershipView, id)
	var i GetPersistedMembershipViewRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.GroupName,
		&i.GroupSource,
		&i.MemberKind,
		&i.MemberID,
		&i.MemberName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEffectiveGroupIDsForMachine = `-- name: ListEffectiveGroupIDsForMachine :many
SELECT gmm.group_id
FROM group_machine_memberships AS gmm
WHERE gmm.machine_id = $1

UNION

SELECT gum.group_id
FROM machines AS m
JOIN users AS u
  ON u.upn = NULLIF(m.primary_user, '')
JOIN group_user_memberships AS gum
  ON gum.user_id = u.id
WHERE m.id = $1

ORDER BY group_id ASC
`

func (q *Queries) ListEffectiveGroupIDsForMachine(ctx context.Context, machineID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEffectiveGroupIDsForMachine, machineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var group_id uuid.UUID
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
