// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const addSyncedGroupMembership = `-- name: AddSyncedGroupMembership :exec
INSERT INTO group_memberships (
  id,
  group_id,
  member_kind,
  member_id,
  origin
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  'synced'
)
ON CONFLICT (group_id, member_kind, member_id) DO UPDATE SET
  origin = 'synced',
  updated_at = NOW()
`

type AddSyncedGroupMembershipParams struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	MemberKind string
	MemberID   uuid.UUID
}

func (q *Queries) AddSyncedGroupMembership(ctx context.Context, arg AddSyncedGroupMembershipParams) error {
	_, err := q.db.Exec(ctx, addSyncedGroupMembership,
		arg.ID,
		arg.GroupID,
		arg.MemberKind,
		arg.MemberID,
	)
	return err
}

const createGroupMembership = `-- name: CreateGroupMembership :one
INSERT INTO group_memberships (
  id,
  group_id,
  member_kind,
  member_id,
  origin
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id,
  group_id,
  member_kind,
  member_id,
  origin,
  created_at,
  updated_at
`

type CreateGroupMembershipParams struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	MemberKind string
	MemberID   uuid.UUID
	Origin     string
}

func (q *Queries) CreateGroupMembership(ctx context.Context, arg CreateGroupMembershipParams) (GroupMembership, error) {
	row := q.db.QueryRow(ctx, createGroupMembership,
		arg.ID,
		arg.GroupID,
		arg.MemberKind,
		arg.MemberID,
		arg.Origin,
	)
	var i GroupMembership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.MemberKind,
		&i.MemberID,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroupMembership = `-- name: DeleteGroupMembership :one
DELETE FROM group_memberships
WHERE id = $1
RETURNING
  id,
  group_id,
  member_kind,
  member_id,
  origin,
  created_at,
  updated_at
`

func (q *Queries) DeleteGroupMembership(ctx context.Context, id uuid.UUID) (GroupMembership, error) {
	row := q.db.QueryRow(ctx, deleteGroupMembership, id)
	var i GroupMembership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.MemberKind,
		&i.MemberID,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupMembership = `-- name: GetGroupMembership :one
SELECT
  id,
  group_id,
  member_kind,
  member_id,
  origin,
  created_at,
  updated_at
FROM group_memberships
WHERE id = $1
`

func (q *Queries) GetGroupMembership(ctx context.Context, id uuid.UUID) (GroupMembership, error) {
	row := q.db.QueryRow(ctx, getGroupMembership, id)
	var i GroupMembership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.MemberKind,
		&i.MemberID,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPersistedGroupMembershipView = `-- name: GetPersistedGroupMembershipView :one
SELECT
  gm.id,
  g.id AS group_id,
  g.name AS group_name,
  g.source AS group_source,
  gm.member_kind,
  gm.member_id,
  CASE
    WHEN gm.member_kind = 'user' THEN NULLIF(u.display_name, '')
    ELSE NULLIF(m.hostname, '')
  END AS member_name,
  gm.created_at,
  gm.updated_at
FROM group_memberships AS gm
JOIN groups AS g
  ON g.id = gm.group_id
LEFT JOIN users AS u
  ON gm.member_kind = 'user'
  AND u.id = gm.member_id
LEFT JOIN machines AS m
  ON gm.member_kind = 'machine'
  AND m.machine_id = gm.member_id
WHERE gm.id = $1
`

type GetPersistedGroupMembershipViewRow struct {
	ID          uuid.UUID
	GroupID     uuid.UUID
	GroupName   string
	GroupSource string
	MemberKind  string
	MemberID    uuid.UUID
	MemberName  interface{}
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetPersistedGroupMembershipView(ctx context.Context, id uuid.UUID) (GetPersistedGroupMembershipViewRow, error) {
	row := q.db.QueryRow(ctx, getPersistedGroupMembershipView, id)
	var i GetPersistedGroupMembershipViewRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.GroupName,
		&i.GroupSource,
		&i.MemberKind,
		&i.MemberID,
		&i.MemberName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEffectiveGroupIDsForMachine = `-- name: ListEffectiveGroupIDsForMachine :many
SELECT gm.group_id
FROM group_memberships AS gm
WHERE gm.member_kind = 'machine'
  AND gm.member_id = $1
UNION
SELECT gm.group_id
FROM group_memberships AS gm
JOIN users AS u
  ON u.id = gm.member_id
  AND gm.member_kind = 'user'
JOIN machines AS m
  ON m.primary_user = u.upn
WHERE m.machine_id = $1
  AND m.primary_user <> ''
`

func (q *Queries) ListEffectiveGroupIDsForMachine(ctx context.Context, memberID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEffectiveGroupIDsForMachine, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var group_id uuid.UUID
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
