// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Executable struct {
	ID             uuid.UUID
	Source         string
	FileSha256     string
	FileName       string
	FilePath       string
	FileBundleID   string
	FileBundlePath string
	SigningID      string
	TeamID         string
	Cdhash         string
	Entitlements   []byte
	SigningChain   []byte
	CreatedAt      time.Time
}

type ExecutionEvent struct {
	ID              uuid.UUID
	MachineID       uuid.UUID
	ExecutableID    uuid.UUID
	Decision        string
	FilePath        string
	ExecutingUser   string
	LoggedInUsers   []string
	CurrentSessions []string
	OccurredAt      *time.Time
	CreatedAt       time.Time
}

type FileAccessEvent struct {
	ID           uuid.UUID
	MachineID    uuid.UUID
	ExecutableID *uuid.UUID
	RuleVersion  string
	RuleName     string
	Target       string
	Decision     string
	ProcessChain []byte
	OccurredAt   *time.Time
	CreatedAt    time.Time
}

type Group struct {
	ID          uuid.UUID
	Name        string
	Description string
	Source      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GroupMembership struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	MemberKind string
	MemberID   uuid.UUID
	Origin     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Machine struct {
	MachineID            uuid.UUID
	SerialNumber         string
	Hostname             string
	ModelIdentifier      string
	OsVersion            string
	OsBuild              string
	SantaVersion         string
	PrimaryUser          string
	PrimaryUserGroupsRaw []byte
	LastSeenAt           time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type MachineRuleSyncState struct {
	MachineID                uuid.UUID
	RequestCleanSync         bool
	LastClientRulesHash      string
	AcknowledgedTargets      []byte
	PendingTargets           []byte
	PendingExpectedRulesHash string
	PendingPayloadRuleCount  int64
	PendingSyncType          string
	PendingPreflightAt       *time.Time
	LastPostflightAt         *time.Time
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

type Rule struct {
	ID            uuid.UUID
	Name          string
	Description   string
	RuleType      string
	Identifier    string
	IdentifierKey pgtype.Text
	CustomMessage string
	CustomUrl     string
	Enabled       bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type RuleTarget struct {
	ID            uuid.UUID
	RuleID        uuid.UUID
	SubjectKind   string
	SubjectID     *uuid.UUID
	Assignment    string
	Priority      pgtype.Int4
	Policy        pgtype.Text
	CelExpression string
}

type User struct {
	ID          uuid.UUID
	Upn         string
	DisplayName string
	Source      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
