// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Executable struct {
	ID             uuid.UUID
	FileSHA256     string
	FileName       string
	FileBundleID   string
	FileBundlePath string
	SigningID      string
	TeamID         string
	Cdhash         string
	Entitlements   []byte
	SigningChain   []byte
	CreatedAt      time.Time
}

type ExecutionEvent struct {
	ID              uuid.UUID
	MachineID       uuid.UUID
	ExecutableID    uuid.UUID
	Decision        string
	FilePath        string
	ExecutingUser   string
	LoggedInUsers   []string
	CurrentSessions []string
	OccurredAt      *time.Time
	CreatedAt       time.Time
}

type FileAccessEvent struct {
	ID           uuid.UUID
	MachineID    uuid.UUID
	RuleVersion  string
	RuleName     string
	Target       string
	Decision     string
	ProcessChain []byte
	OccurredAt   *time.Time
	CreatedAt    time.Time
}

type Group struct {
	ID          uuid.UUID
	Name        string
	Description string
	Source      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Machine struct {
	MachineID            uuid.UUID
	SerialNumber         string
	Hostname             string
	ModelIdentifier      string
	OsVersion            string
	OsBuild              string
	SantaVersion         string
	PrimaryUser          string
	PrimaryUserGroupsRaw []byte
	LastSeenAt           time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type MachineSyncState struct {
	MachineID                   uuid.UUID
	RulesHash                   string
	AppliedTargets              []byte
	PendingTargets              []byte
	PendingPayloadRuleCount     int64
	PendingPreflightAt          *time.Time
	LastRuleSyncSuccessAt       *time.Time
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	PendingFullSync             bool
	ClientMode                  string
	BinaryRuleCount             int32
	CertificateRuleCount        int32
	CompilerRuleCount           int32
	TransitiveRuleCount         int32
	TeamIDRuleCount             int32
	SigningIDRuleCount          int32
	CDHashRuleCount             int32
	RulesReceived               int32
	RulesProcessed              int32
	LastRuleSyncAttemptAt       *time.Time
	PendingPayload              []byte
	DesiredTargets              []byte
	DesiredBinaryRuleCount      int32
	DesiredCertificateRuleCount int32
	DesiredTeamIDRuleCount      int32
	DesiredSigningIDRuleCount   int32
	DesiredCDHashRuleCount      int32
	LastCleanSyncAt             *time.Time
	LastReportedCountsMatchAt   *time.Time
}

type Membership struct {
	ID         uuid.UUID
	GroupID    uuid.UUID
	MemberKind string
	MemberID   uuid.UUID
	Origin     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Rule struct {
	ID            uuid.UUID
	Name          string
	Description   string
	RuleType      string
	Identifier    string
	CustomMessage string
	CustomURL     string
	Enabled       bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type RuleTarget struct {
	ID            uuid.UUID
	RuleID        uuid.UUID
	SubjectKind   string
	SubjectID     *uuid.UUID
	Assignment    string
	Priority      pgtype.Int4
	Policy        pgtype.Text
	CelExpression string
}

type User struct {
	ID          uuid.UUID
	Upn         string
	DisplayName string
	Source      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
