// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countGroupsByIDs = `-- name: CountGroupsByIDs :one
SELECT COUNT(*)::INT4
FROM groups
WHERE id = ANY($1::UUID[])
`

func (q *Queries) CountGroupsByIDs(ctx context.Context, groupIds []uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countGroupsByIDs, groupIds)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countRulesByIDs = `-- name: CountRulesByIDs :one
SELECT COUNT(*)::INT4
FROM rules
WHERE id = ANY($1::UUID[])
`

func (q *Queries) CountRulesByIDs(ctx context.Context, ruleIds []uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countRulesByIDs, ruleIds)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createRule = `-- name: CreateRule :one
INSERT INTO rules (
  id,
  name,
  description,
  rule_type,
  identifier,
  custom_message,
  custom_url
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING
  id,
  name,
  description,
  rule_type,
  identifier,
  custom_message,
  custom_url,
  created_at,
  updated_at
`

type CreateRuleParams struct {
	ID            uuid.UUID
	Name          string
	Description   string
	RuleType      string
	Identifier    string
	CustomMessage string
	CustomUrl     string
}

type CreateRuleRow struct {
	ID            uuid.UUID
	Name          string
	Description   string
	RuleType      string
	Identifier    string
	CustomMessage string
	CustomUrl     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (CreateRuleRow, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.RuleType,
		arg.Identifier,
		arg.CustomMessage,
		arg.CustomUrl,
	)
	var i CreateRuleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RuleType,
		&i.Identifier,
		&i.CustomMessage,
		&i.CustomUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :one
DELETE FROM rules
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteRule(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteRule, id)
	err := row.Scan(&id)
	return id, err
}

const getRule = `-- name: GetRule :one
SELECT
  id,
  name,
  description,
  rule_type,
  identifier,
  custom_message,
  custom_url,
  created_at,
  updated_at
FROM rules
WHERE id = $1
`

type GetRuleRow struct {
	ID            uuid.UUID
	Name          string
	Description   string
	RuleType      string
	Identifier    string
	CustomMessage string
	CustomUrl     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetRule(ctx context.Context, id uuid.UUID) (GetRuleRow, error) {
	row := q.db.QueryRow(ctx, getRule, id)
	var i GetRuleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RuleType,
		&i.Identifier,
		&i.CustomMessage,
		&i.CustomUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResolvedRulesForMachine = `-- name: ListResolvedRulesForMachine :many
WITH effective_groups AS (
  SELECT gm.group_id
  FROM group_memberships AS gm
  WHERE gm.member_kind = 'machine'
    AND gm.member_id = $1
  UNION
  SELECT gm.group_id
  FROM group_memberships AS gm
  JOIN users AS u
    ON u.id = gm.member_id
    AND gm.member_kind = 'user'
  JOIN machines AS m
    ON m.primary_user = u.upn
  WHERE m.machine_id = $1
    AND m.primary_user <> ''
),
matching_excludes AS (
  SELECT DISTINCT rt.rule_id
  FROM rule_targets AS rt
  JOIN effective_groups AS eg
    ON eg.group_id = rt.subject_id
  WHERE rt.assignment = 'exclude'
    AND rt.subject_kind = 'group'
),
matching_includes AS (
  SELECT
    rt.rule_id,
    rt.subject_id,
    rt.priority,
    rt.policy,
    rt.cel_expression,
    ROW_NUMBER() OVER (
      PARTITION BY rt.rule_id
      ORDER BY rt.priority ASC, rt.subject_id ASC
    ) AS include_rank
  FROM rule_targets AS rt
  JOIN effective_groups AS eg
    ON eg.group_id = rt.subject_id
  WHERE rt.assignment = 'include'
    AND rt.subject_kind = 'group'
),
winning_includes AS (
  SELECT
    rule_id,
    subject_id,
    priority,
    policy,
    cel_expression
  FROM matching_includes
  WHERE include_rank = 1
)
SELECT
  r.id,
  r.name,
  r.rule_type,
  r.identifier,
  r.identifier_key,
  r.custom_message,
  r.custom_url,
  wi.subject_id AS matched_group_id,
  wi.priority AS matched_priority,
  wi.policy,
  wi.cel_expression
FROM rules AS r
JOIN winning_includes AS wi
  ON wi.rule_id = r.id
LEFT JOIN matching_excludes AS me
  ON me.rule_id = r.id
WHERE me.rule_id IS NULL
ORDER BY r.rule_type ASC, r.identifier_key ASC, r.id ASC
`

type ListResolvedRulesForMachineRow struct {
	ID              uuid.UUID
	Name            string
	RuleType        string
	Identifier      string
	IdentifierKey   pgtype.Text
	CustomMessage   string
	CustomUrl       string
	MatchedGroupID  uuid.UUID
	MatchedPriority pgtype.Int4
	Policy          pgtype.Text
	CelExpression   string
}

func (q *Queries) ListResolvedRulesForMachine(ctx context.Context, memberID uuid.UUID) ([]ListResolvedRulesForMachineRow, error) {
	rows, err := q.db.Query(ctx, listResolvedRulesForMachine, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResolvedRulesForMachineRow
	for rows.Next() {
		var i ListResolvedRulesForMachineRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RuleType,
			&i.Identifier,
			&i.IdentifierKey,
			&i.CustomMessage,
			&i.CustomUrl,
			&i.MatchedGroupID,
			&i.MatchedPriority,
			&i.Policy,
			&i.CelExpression,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT
  id,
  name,
  description,
  rule_type,
  identifier,
  custom_message,
  custom_url,
  created_at,
  updated_at
FROM rules
ORDER BY created_at DESC, id DESC
LIMIT $1
OFFSET $2
`

type ListRulesParams struct {
	Limit  int32
	Offset int32
}

type ListRulesRow struct {
	ID            uuid.UUID
	Name          string
	Description   string
	RuleType      string
	Identifier    string
	CustomMessage string
	CustomUrl     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListRules(ctx context.Context, arg ListRulesParams) ([]ListRulesRow, error) {
	rows, err := q.db.Query(ctx, listRules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRulesRow
	for rows.Next() {
		var i ListRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RuleType,
			&i.Identifier,
			&i.CustomMessage,
			&i.CustomUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :one
UPDATE rules
SET
  name = $2,
  description = $3,
  rule_type = $4,
  identifier = $5,
  custom_message = $6,
  custom_url = $7,
  updated_at = NOW()
WHERE id = $1
RETURNING
  id,
  name,
  description,
  rule_type,
  identifier,
  custom_message,
  custom_url,
  created_at,
  updated_at
`

type UpdateRuleParams struct {
	ID            uuid.UUID
	Name          string
	Description   string
	RuleType      string
	Identifier    string
	CustomMessage string
	CustomUrl     string
}

type UpdateRuleRow struct {
	ID            uuid.UUID
	Name          string
	Description   string
	RuleType      string
	Identifier    string
	CustomMessage string
	CustomUrl     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (UpdateRuleRow, error) {
	row := q.db.QueryRow(ctx, updateRule,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.RuleType,
		arg.Identifier,
		arg.CustomMessage,
		arg.CustomUrl,
	)
	var i UpdateRuleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RuleType,
		&i.Identifier,
		&i.CustomMessage,
		&i.CustomUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
