// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rule_targets.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRuleTarget = `-- name: CreateRuleTarget :exec
INSERT INTO rule_targets (
  id,
  rule_id,
  subject_kind,
  subject_id,
  assignment,
  priority,
  policy,
  cel_expression
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
`

type CreateRuleTargetParams struct {
	ID            uuid.UUID
	RuleID        uuid.UUID
	SubjectKind   string
	SubjectID     *uuid.UUID
	Assignment    string
	Priority      pgtype.Int4
	Policy        pgtype.Text
	CelExpression string
}

func (q *Queries) CreateRuleTarget(ctx context.Context, arg CreateRuleTargetParams) error {
	_, err := q.db.Exec(ctx, createRuleTarget,
		arg.ID,
		arg.RuleID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Assignment,
		arg.Priority,
		arg.Policy,
		arg.CelExpression,
	)
	return err
}

const deleteRuleTargetsByRule = `-- name: DeleteRuleTargetsByRule :exec
DELETE FROM rule_targets
WHERE rule_id = $1
`

func (q *Queries) DeleteRuleTargetsByRule(ctx context.Context, ruleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRuleTargetsByRule, ruleID)
	return err
}

const listRuleTargetsByRule = `-- name: ListRuleTargetsByRule :many
SELECT
  rt.subject_kind,
  rt.subject_id,
  rt.assignment,
  rt.priority,
  rt.policy,
  rt.cel_expression,
  CASE
    WHEN rt.subject_kind = 'group' THEN COALESCE(g.name, '')
    WHEN rt.subject_kind = 'all_devices' THEN 'All Devices'
    WHEN rt.subject_kind = 'all_users' THEN 'All Users'
    ELSE ''
  END AS subject_name
FROM rule_targets AS rt
LEFT JOIN groups AS g
  ON rt.subject_kind = 'group'
  AND g.id = rt.subject_id
WHERE rt.rule_id = $1
ORDER BY
  CASE WHEN rt.assignment = 'include' THEN 0 ELSE 1 END ASC,
  rt.priority ASC NULLS LAST,
  rt.subject_kind ASC,
  rt.subject_id ASC
`

type ListRuleTargetsByRuleRow struct {
	SubjectKind   string
	SubjectID     *uuid.UUID
	Assignment    string
	Priority      pgtype.Int4
	Policy        pgtype.Text
	CelExpression string
	SubjectName   string
}

func (q *Queries) ListRuleTargetsByRule(ctx context.Context, ruleID uuid.UUID) ([]ListRuleTargetsByRuleRow, error) {
	rows, err := q.db.Query(ctx, listRuleTargetsByRule, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRuleTargetsByRuleRow
	for rows.Next() {
		var i ListRuleTargetsByRuleRow
		if err := rows.Scan(
			&i.SubjectKind,
			&i.SubjectID,
			&i.Assignment,
			&i.Priority,
			&i.Policy,
			&i.CelExpression,
			&i.SubjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
