// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rule_targets.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRuleTarget = `-- name: CreateRuleTarget :one
INSERT INTO rule_targets (
  id,
  rule_id,
  subject_kind,
  subject_id,
  assignment,
  priority,
  policy,
  cel_expression
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING
  id,
  rule_id,
  subject_kind,
  subject_id,
  assignment,
  priority,
  policy,
  cel_expression,
  created_at,
  updated_at
`

type CreateRuleTargetParams struct {
	ID            uuid.UUID
	RuleID        uuid.UUID
	SubjectKind   string
	SubjectID     uuid.UUID
	Assignment    string
	Priority      pgtype.Int4
	Policy        pgtype.Text
	CelExpression string
}

func (q *Queries) CreateRuleTarget(ctx context.Context, arg CreateRuleTargetParams) (RuleTarget, error) {
	row := q.db.QueryRow(ctx, createRuleTarget,
		arg.ID,
		arg.RuleID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Assignment,
		arg.Priority,
		arg.Policy,
		arg.CelExpression,
	)
	var i RuleTarget
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Assignment,
		&i.Priority,
		&i.Policy,
		&i.CelExpression,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRuleTarget = `-- name: DeleteRuleTarget :one
DELETE FROM rule_targets
WHERE id = $1
RETURNING
  id,
  rule_id,
  subject_kind,
  subject_id,
  assignment,
  priority,
  policy,
  cel_expression,
  created_at,
  updated_at
`

func (q *Queries) DeleteRuleTarget(ctx context.Context, id uuid.UUID) (RuleTarget, error) {
	row := q.db.QueryRow(ctx, deleteRuleTarget, id)
	var i RuleTarget
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Assignment,
		&i.Priority,
		&i.Policy,
		&i.CelExpression,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuleTarget = `-- name: GetRuleTarget :one
SELECT
  id,
  rule_id,
  subject_kind,
  subject_id,
  assignment,
  priority,
  policy,
  cel_expression,
  created_at,
  updated_at
FROM rule_targets
WHERE id = $1
`

func (q *Queries) GetRuleTarget(ctx context.Context, id uuid.UUID) (RuleTarget, error) {
	row := q.db.QueryRow(ctx, getRuleTarget, id)
	var i RuleTarget
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Assignment,
		&i.Priority,
		&i.Policy,
		&i.CelExpression,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRuleTargetsByRule = `-- name: ListRuleTargetsByRule :many
SELECT
  id,
  rule_id,
  subject_kind,
  subject_id,
  assignment,
  priority,
  policy,
  cel_expression,
  created_at,
  updated_at
FROM rule_targets
WHERE rule_id = $1
ORDER BY
  CASE WHEN assignment = 'include' THEN 0 ELSE 1 END ASC,
  priority ASC NULLS LAST,
  subject_id ASC
`

func (q *Queries) ListRuleTargetsByRule(ctx context.Context, ruleID uuid.UUID) ([]RuleTarget, error) {
	rows, err := q.db.Query(ctx, listRuleTargetsByRule, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuleTarget
	for rows.Next() {
		var i RuleTarget
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Assignment,
			&i.Priority,
			&i.Policy,
			&i.CelExpression,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRuleTarget = `-- name: UpdateRuleTarget :one
UPDATE rule_targets
SET
  subject_kind = $2,
  subject_id = $3,
  assignment = $4,
  priority = $5,
  policy = $6,
  cel_expression = $7,
  updated_at = NOW()
WHERE id = $1
RETURNING
  id,
  rule_id,
  subject_kind,
  subject_id,
  assignment,
  priority,
  policy,
  cel_expression,
  created_at,
  updated_at
`

type UpdateRuleTargetParams struct {
	ID            uuid.UUID
	SubjectKind   string
	SubjectID     uuid.UUID
	Assignment    string
	Priority      pgtype.Int4
	Policy        pgtype.Text
	CelExpression string
}

func (q *Queries) UpdateRuleTarget(ctx context.Context, arg UpdateRuleTargetParams) (RuleTarget, error) {
	row := q.db.QueryRow(ctx, updateRuleTarget,
		arg.ID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Assignment,
		arg.Priority,
		arg.Policy,
		arg.CelExpression,
	)
	var i RuleTarget
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Assignment,
		&i.Priority,
		&i.Policy,
		&i.CelExpression,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
