-- name: GetMachineSyncState :one
SELECT
  m.machine_id,
  COALESCE(ms.rules_hash, '') AS rules_hash,
  COALESCE(ms.applied_targets, '[]'::JSONB) AS applied_targets,
  COALESCE(ms.pending_targets, '[]'::JSONB) AS pending_targets,
  COALESCE(ms.expected_rules_hash, '') AS expected_rules_hash,
  COALESCE(ms.pending_payload_rule_count, 0)::INT8 AS pending_payload_rule_count,
  COALESCE(ms.pending_full_sync, FALSE) AS pending_full_sync,
  ms.pending_preflight_at,
  COALESCE(ms.client_mode, 'unknown') AS client_mode,
  COALESCE(ms.binary_rule_count, 0)::INT4 AS binary_rule_count,
  COALESCE(ms.certificate_rule_count, 0)::INT4 AS certificate_rule_count,
  COALESCE(ms.compiler_rule_count, 0)::INT4 AS compiler_rule_count,
  COALESCE(ms.transitive_rule_count, 0)::INT4 AS transitive_rule_count,
  COALESCE(ms.teamid_rule_count, 0)::INT4 AS teamid_rule_count,
  COALESCE(ms.signingid_rule_count, 0)::INT4 AS signingid_rule_count,
  COALESCE(ms.cdhash_rule_count, 0)::INT4 AS cdhash_rule_count,
  COALESCE(ms.rules_received, 0)::INT4 AS rules_received,
  COALESCE(ms.rules_processed, 0)::INT4 AS rules_processed,
  ms.last_rule_sync_attempt_at,
  ms.last_rule_sync_success_at
FROM machines AS m
LEFT JOIN machine_sync_states AS ms
  ON ms.machine_id = m.machine_id
WHERE m.machine_id = $1;

-- name: UpsertMachineSyncState :one
INSERT INTO machine_sync_states (
  machine_id,
  rules_hash,
  applied_targets,
  pending_targets,
  expected_rules_hash,
  pending_payload_rule_count,
  pending_full_sync,
  pending_preflight_at,
  client_mode,
  binary_rule_count,
  certificate_rule_count,
  compiler_rule_count,
  transitive_rule_count,
  teamid_rule_count,
  signingid_rule_count,
  cdhash_rule_count,
  rules_received,
  rules_processed,
  last_rule_sync_attempt_at,
  last_rule_sync_success_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20
)
ON CONFLICT (machine_id) DO UPDATE SET
  rules_hash = EXCLUDED.rules_hash,
  applied_targets = EXCLUDED.applied_targets,
  pending_targets = EXCLUDED.pending_targets,
  expected_rules_hash = EXCLUDED.expected_rules_hash,
  pending_payload_rule_count = EXCLUDED.pending_payload_rule_count,
  pending_full_sync = EXCLUDED.pending_full_sync,
  pending_preflight_at = EXCLUDED.pending_preflight_at,
  client_mode = EXCLUDED.client_mode,
  binary_rule_count = EXCLUDED.binary_rule_count,
  certificate_rule_count = EXCLUDED.certificate_rule_count,
  compiler_rule_count = EXCLUDED.compiler_rule_count,
  transitive_rule_count = EXCLUDED.transitive_rule_count,
  teamid_rule_count = EXCLUDED.teamid_rule_count,
  signingid_rule_count = EXCLUDED.signingid_rule_count,
  cdhash_rule_count = EXCLUDED.cdhash_rule_count,
  rules_received = EXCLUDED.rules_received,
  rules_processed = EXCLUDED.rules_processed,
  last_rule_sync_attempt_at = EXCLUDED.last_rule_sync_attempt_at,
  last_rule_sync_success_at = EXCLUDED.last_rule_sync_success_at,
  updated_at = NOW()
RETURNING
  machine_id,
  rules_hash,
  applied_targets,
  pending_targets,
  expected_rules_hash,
  pending_payload_rule_count,
  pending_full_sync,
  pending_preflight_at,
  client_mode,
  binary_rule_count,
  certificate_rule_count,
  compiler_rule_count,
  transitive_rule_count,
  teamid_rule_count,
  signingid_rule_count,
  cdhash_rule_count,
  rules_received,
  rules_processed,
  last_rule_sync_attempt_at,
  last_rule_sync_success_at,
  created_at,
  updated_at;
