// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package httpapi

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
	domain "github.com/woodleighschool/grinch/internal/domain"
)

const (
	SessionAuthScopes = "sessionAuth.Scopes"
)

// Defines values for Order.
const (
	OrderAsc  Order = "asc"
	OrderDesc Order = "desc"
)

// Valid indicates whether the value is a known member of the Order enum.
func (e Order) Valid() bool {
	switch e {
	case OrderAsc:
		return true
	case OrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListExecutablesParamsOrder.
const (
	ListExecutablesParamsOrderAsc  ListExecutablesParamsOrder = "asc"
	ListExecutablesParamsOrderDesc ListExecutablesParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListExecutablesParamsOrder enum.
func (e ListExecutablesParamsOrder) Valid() bool {
	switch e {
	case ListExecutablesParamsOrderAsc:
		return true
	case ListExecutablesParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListExecutionEventsParamsOrder.
const (
	ListExecutionEventsParamsOrderAsc  ListExecutionEventsParamsOrder = "asc"
	ListExecutionEventsParamsOrderDesc ListExecutionEventsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListExecutionEventsParamsOrder enum.
func (e ListExecutionEventsParamsOrder) Valid() bool {
	switch e {
	case ListExecutionEventsParamsOrderAsc:
		return true
	case ListExecutionEventsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListFileAccessEventsParamsOrder.
const (
	ListFileAccessEventsParamsOrderAsc  ListFileAccessEventsParamsOrder = "asc"
	ListFileAccessEventsParamsOrderDesc ListFileAccessEventsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListFileAccessEventsParamsOrder enum.
func (e ListFileAccessEventsParamsOrder) Valid() bool {
	switch e {
	case ListFileAccessEventsParamsOrderAsc:
		return true
	case ListFileAccessEventsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListGroupMembershipsParamsOrder.
const (
	ListGroupMembershipsParamsOrderAsc  ListGroupMembershipsParamsOrder = "asc"
	ListGroupMembershipsParamsOrderDesc ListGroupMembershipsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListGroupMembershipsParamsOrder enum.
func (e ListGroupMembershipsParamsOrder) Valid() bool {
	switch e {
	case ListGroupMembershipsParamsOrderAsc:
		return true
	case ListGroupMembershipsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListGroupsParamsOrder.
const (
	ListGroupsParamsOrderAsc  ListGroupsParamsOrder = "asc"
	ListGroupsParamsOrderDesc ListGroupsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListGroupsParamsOrder enum.
func (e ListGroupsParamsOrder) Valid() bool {
	switch e {
	case ListGroupsParamsOrderAsc:
		return true
	case ListGroupsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListMachinesParamsOrder.
const (
	ListMachinesParamsOrderAsc  ListMachinesParamsOrder = "asc"
	ListMachinesParamsOrderDesc ListMachinesParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListMachinesParamsOrder enum.
func (e ListMachinesParamsOrder) Valid() bool {
	switch e {
	case ListMachinesParamsOrderAsc:
		return true
	case ListMachinesParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListRulesParamsOrder.
const (
	ListRulesParamsOrderAsc  ListRulesParamsOrder = "asc"
	ListRulesParamsOrderDesc ListRulesParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListRulesParamsOrder enum.
func (e ListRulesParamsOrder) Valid() bool {
	switch e {
	case ListRulesParamsOrderAsc:
		return true
	case ListRulesParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListUsersParamsOrder.
const (
	Asc  ListUsersParamsOrder = "asc"
	Desc ListUsersParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListUsersParamsOrder enum.
func (e ListUsersParamsOrder) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// EventDecision defines model for EventDecision.
type EventDecision = domain.EventDecision

// ExcludedGroup defines model for ExcludedGroup.
type ExcludedGroup = domain.ExcludedGroup

// Executable defines model for Executable.
type Executable = domain.ExecutableSummary

// ExecutableListResponse defines model for ExecutableListResponse.
type ExecutableListResponse struct {
	Rows  []ExecutableSummary `json:"rows"`
	Total int32               `json:"total"`
}

// ExecutableSource defines model for ExecutableSource.
type ExecutableSource = domain.ExecutableSource

// ExecutableSummary defines model for ExecutableSummary.
type ExecutableSummary = domain.ExecutableSummary

// ExecutionEvent defines model for ExecutionEvent.
type ExecutionEvent = domain.ExecutionEvent

// ExecutionEventListResponse defines model for ExecutionEventListResponse.
type ExecutionEventListResponse struct {
	Rows  []ExecutionEventSummary `json:"rows"`
	Total int32                   `json:"total"`
}

// ExecutionEventSummary defines model for ExecutionEventSummary.
type ExecutionEventSummary = domain.ExecutionEventSummary

// FieldError defines model for FieldError.
type FieldError struct {
	Code    *string `json:"code,omitempty"`
	Field   string  `json:"field"`
	Message string  `json:"message"`
}

// FileAccessDecision defines model for FileAccessDecision.
type FileAccessDecision = domain.FileAccessDecision

// FileAccessEvent defines model for FileAccessEvent.
type FileAccessEvent = domain.FileAccessEvent

// FileAccessEventListResponse defines model for FileAccessEventListResponse.
type FileAccessEventListResponse struct {
	Rows  []FileAccessEventSummary `json:"rows"`
	Total int32                    `json:"total"`
}

// FileAccessEventProcess defines model for FileAccessEventProcess.
type FileAccessEventProcess = domain.FileAccessEventProcess

// FileAccessEventSummary defines model for FileAccessEventSummary.
type FileAccessEventSummary = domain.FileAccessEventSummary

// Group defines model for Group.
type Group = domain.Group

// GroupCreateRequest defines model for GroupCreateRequest.
type GroupCreateRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// GroupListResponse defines model for GroupListResponse.
type GroupListResponse struct {
	Rows  []Group `json:"rows"`
	Total int32   `json:"total"`
}

// GroupMembership defines model for GroupMembership.
type GroupMembership = domain.GroupMembership

// GroupMembershipCreateRequest defines model for GroupMembershipCreateRequest.
type GroupMembershipCreateRequest struct {
	GroupId    openapi_types.UUID `json:"group_id"`
	MemberId   openapi_types.UUID `json:"member_id"`
	MemberKind MemberKind         `json:"member_kind"`
}

// GroupMembershipGroup defines model for GroupMembershipGroup.
type GroupMembershipGroup = domain.GroupMembershipGroup

// GroupMembershipKind defines model for GroupMembershipKind.
type GroupMembershipKind = domain.GroupMembershipKind

// GroupMembershipListResponse defines model for GroupMembershipListResponse.
type GroupMembershipListResponse struct {
	Rows  []GroupMembership `json:"rows"`
	Total int32             `json:"total"`
}

// GroupMembershipMember defines model for GroupMembershipMember.
type GroupMembershipMember = domain.GroupMembershipMember

// IncludeRuleTarget defines model for IncludeRuleTarget.
type IncludeRuleTarget = domain.IncludeRuleTarget

// Machine defines model for Machine.
type Machine = domain.Machine

// MachineListResponse defines model for MachineListResponse.
type MachineListResponse struct {
	Rows  []MachineSummary `json:"rows"`
	Total int32            `json:"total"`
}

// MachineSummary defines model for MachineSummary.
type MachineSummary = domain.MachineSummary

// MemberKind defines model for MemberKind.
type MemberKind = domain.MemberKind

// Problem defines model for Problem.
type Problem struct {
	Code        string        `json:"code"`
	Detail      string        `json:"detail"`
	FieldErrors *[]FieldError `json:"field_errors,omitempty"`
	Status      int32         `json:"status"`
	Title       string        `json:"title"`
	Type        string        `json:"type"`
}

// Rule defines model for Rule.
type Rule = domain.RuleSummary

// RuleCreateRequest defines model for RuleCreateRequest.
type RuleCreateRequest struct {
	CustomMessage *string `json:"custom_message,omitempty"`
	CustomUrl     *string `json:"custom_url,omitempty"`
	Description   *string `json:"description,omitempty"`

	// Enabled Default true when omitted.
	Enabled    *bool       `json:"enabled,omitempty"`
	Identifier string      `json:"identifier"`
	Name       string      `json:"name"`
	RuleType   RuleType    `json:"rule_type"`
	Targets    RuleTargets `json:"targets"`
}

// RuleListResponse defines model for RuleListResponse.
type RuleListResponse struct {
	Rows  []RuleSummary `json:"rows"`
	Total int32         `json:"total"`
}

// RulePolicy defines model for RulePolicy.
type RulePolicy = domain.RulePolicy

// RuleSummary defines model for RuleSummary.
type RuleSummary = domain.RuleSummary

// RuleTargetSubjectKind defines model for RuleTargetSubjectKind.
type RuleTargetSubjectKind = domain.RuleTargetSubjectKind

// RuleTargets defines model for RuleTargets.
type RuleTargets = domain.RuleTargets

// RuleType defines model for RuleType.
type RuleType = domain.RuleType

// RuleUpdateRequest defines model for RuleUpdateRequest.
type RuleUpdateRequest = RuleCreateRequest

// SigningChainEntry defines model for SigningChainEntry.
type SigningChainEntry = domain.SigningChainEntry

// Source defines model for Source.
type Source = domain.PrincipalSource

// User defines model for User.
type User = domain.User

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	Rows  []User `json:"rows"`
	Total int32  `json:"total"`
}

// ExecutableIdFilter defines model for ExecutableIdFilter.
type ExecutableIdFilter = openapi_types.UUID

// GroupIdFilter defines model for GroupIdFilter.
type GroupIdFilter = openapi_types.UUID

// GroupMembershipId defines model for GroupMembershipId.
type GroupMembershipId = openapi_types.UUID

// Id defines model for Id.
type Id = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int32

// MachineIdFilter defines model for MachineIdFilter.
type MachineIdFilter = openapi_types.UUID

// Offset defines model for Offset.
type Offset = int32

// Order defines model for Order.
type Order string

// RuleIdFilter defines model for RuleIdFilter.
type RuleIdFilter = openapi_types.UUID

// RulePolicyFilter defines model for RulePolicyFilter.
type RulePolicyFilter = RulePolicy

// Search defines model for Search.
type Search = string

// Sort defines model for Sort.
type Sort = string

// SubjectIdFilter defines model for SubjectIdFilter.
type SubjectIdFilter = openapi_types.UUID

// SubjectKindFilter defines model for SubjectKindFilter.
type SubjectKindFilter = RuleTargetSubjectKind

// UserIdFilter defines model for UserIdFilter.
type UserIdFilter = openapi_types.UUID

// NotFound defines model for NotFound.
type NotFound = Problem

// ListExecutablesParams defines parameters for ListExecutables.
type ListExecutablesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort  *Sort                       `form:"sort,omitempty" json:"sort,omitempty"`
	Order *ListExecutablesParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// ListExecutablesParamsOrder defines parameters for ListExecutables.
type ListExecutablesParamsOrder string

// ListExecutionEventsParams defines parameters for ListExecutionEvents.
type ListExecutionEventsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort         *Sort                           `form:"sort,omitempty" json:"sort,omitempty"`
	Order        *ListExecutionEventsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	MachineId    *MachineIdFilter                `form:"machine_id,omitempty" json:"machine_id,omitempty"`
	UserId       *UserIdFilter                   `form:"user_id,omitempty" json:"user_id,omitempty"`
	ExecutableId *ExecutableIdFilter             `form:"executable_id,omitempty" json:"executable_id,omitempty"`
}

// ListExecutionEventsParamsOrder defines parameters for ListExecutionEvents.
type ListExecutionEventsParamsOrder string

// ListFileAccessEventsParams defines parameters for ListFileAccessEvents.
type ListFileAccessEventsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort         *Sort                            `form:"sort,omitempty" json:"sort,omitempty"`
	Order        *ListFileAccessEventsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	MachineId    *MachineIdFilter                 `form:"machine_id,omitempty" json:"machine_id,omitempty"`
	ExecutableId *ExecutableIdFilter              `form:"executable_id,omitempty" json:"executable_id,omitempty"`
}

// ListFileAccessEventsParamsOrder defines parameters for ListFileAccessEvents.
type ListFileAccessEventsParamsOrder string

// ListGroupMembershipsParams defines parameters for ListGroupMemberships.
type ListGroupMembershipsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort      *Sort                            `form:"sort,omitempty" json:"sort,omitempty"`
	Order     *ListGroupMembershipsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	GroupId   *GroupIdFilter                   `form:"group_id,omitempty" json:"group_id,omitempty"`
	UserId    *UserIdFilter                    `form:"user_id,omitempty" json:"user_id,omitempty"`
	MachineId *MachineIdFilter                 `form:"machine_id,omitempty" json:"machine_id,omitempty"`
}

// ListGroupMembershipsParamsOrder defines parameters for ListGroupMemberships.
type ListGroupMembershipsParamsOrder string

// ListGroupsParams defines parameters for ListGroups.
type ListGroupsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort  *Sort                  `form:"sort,omitempty" json:"sort,omitempty"`
	Order *ListGroupsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// ListGroupsParamsOrder defines parameters for ListGroups.
type ListGroupsParamsOrder string

// ListMachinesParams defines parameters for ListMachines.
type ListMachinesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort   *Sort                    `form:"sort,omitempty" json:"sort,omitempty"`
	Order  *ListMachinesParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	UserId *UserIdFilter            `form:"user_id,omitempty" json:"user_id,omitempty"`
}

// ListMachinesParamsOrder defines parameters for ListMachines.
type ListMachinesParamsOrder string

// ListRulesParams defines parameters for ListRules.
type ListRulesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort  *Sort                 `form:"sort,omitempty" json:"sort,omitempty"`
	Order *ListRulesParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// ListRulesParamsOrder defines parameters for ListRules.
type ListRulesParamsOrder string

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort  *Sort                 `form:"sort,omitempty" json:"sort,omitempty"`
	Order *ListUsersParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// ListUsersParamsOrder defines parameters for ListUsers.
type ListUsersParamsOrder string

// CreateGroupMembershipJSONRequestBody defines body for CreateGroupMembership for application/json ContentType.
type CreateGroupMembershipJSONRequestBody = GroupMembershipCreateRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = GroupCreateRequest

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody = GroupCreateRequest

// CreateRuleJSONRequestBody defines body for CreateRule for application/json ContentType.
type CreateRuleJSONRequestBody = RuleCreateRequest

// UpdateRuleJSONRequestBody defines body for UpdateRule for application/json ContentType.
type UpdateRuleJSONRequestBody = RuleUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /executables)
	ListExecutables(w http.ResponseWriter, r *http.Request, params ListExecutablesParams)

	// (GET /executables/{id})
	GetExecutable(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /execution-events)
	ListExecutionEvents(w http.ResponseWriter, r *http.Request, params ListExecutionEventsParams)

	// (DELETE /execution-events/{id})
	DeleteExecutionEvent(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /execution-events/{id})
	GetExecutionEvent(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /file-access-events)
	ListFileAccessEvents(w http.ResponseWriter, r *http.Request, params ListFileAccessEventsParams)

	// (DELETE /file-access-events/{id})
	DeleteFileAccessEvent(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /file-access-events/{id})
	GetFileAccessEvent(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /group-memberships)
	ListGroupMemberships(w http.ResponseWriter, r *http.Request, params ListGroupMembershipsParams)

	// (POST /group-memberships)
	CreateGroupMembership(w http.ResponseWriter, r *http.Request)

	// (DELETE /group-memberships/{id})
	DeleteGroupMembership(w http.ResponseWriter, r *http.Request, id GroupMembershipId)

	// (GET /group-memberships/{id})
	GetGroupMembership(w http.ResponseWriter, r *http.Request, id GroupMembershipId)

	// (GET /groups)
	ListGroups(w http.ResponseWriter, r *http.Request, params ListGroupsParams)

	// (POST /groups)
	CreateGroup(w http.ResponseWriter, r *http.Request)

	// (DELETE /groups/{id})
	DeleteGroup(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /groups/{id})
	GetGroup(w http.ResponseWriter, r *http.Request, id Id)

	// (PUT /groups/{id})
	UpdateGroup(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /machines)
	ListMachines(w http.ResponseWriter, r *http.Request, params ListMachinesParams)

	// (DELETE /machines/{id})
	DeleteMachine(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /machines/{id})
	GetMachine(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /rules)
	ListRules(w http.ResponseWriter, r *http.Request, params ListRulesParams)

	// (POST /rules)
	CreateRule(w http.ResponseWriter, r *http.Request)

	// (DELETE /rules/{id})
	DeleteRule(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /rules/{id})
	GetRule(w http.ResponseWriter, r *http.Request, id Id)

	// (PUT /rules/{id})
	UpdateRule(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)

	// (GET /users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id Id)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /executables)
func (_ Unimplemented) ListExecutables(w http.ResponseWriter, r *http.Request, params ListExecutablesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /executables/{id})
func (_ Unimplemented) GetExecutable(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /execution-events)
func (_ Unimplemented) ListExecutionEvents(w http.ResponseWriter, r *http.Request, params ListExecutionEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /execution-events/{id})
func (_ Unimplemented) DeleteExecutionEvent(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /execution-events/{id})
func (_ Unimplemented) GetExecutionEvent(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /file-access-events)
func (_ Unimplemented) ListFileAccessEvents(w http.ResponseWriter, r *http.Request, params ListFileAccessEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /file-access-events/{id})
func (_ Unimplemented) DeleteFileAccessEvent(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /file-access-events/{id})
func (_ Unimplemented) GetFileAccessEvent(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /group-memberships)
func (_ Unimplemented) ListGroupMemberships(w http.ResponseWriter, r *http.Request, params ListGroupMembershipsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /group-memberships)
func (_ Unimplemented) CreateGroupMembership(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /group-memberships/{id})
func (_ Unimplemented) DeleteGroupMembership(w http.ResponseWriter, r *http.Request, id GroupMembershipId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /group-memberships/{id})
func (_ Unimplemented) GetGroupMembership(w http.ResponseWriter, r *http.Request, id GroupMembershipId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /groups)
func (_ Unimplemented) ListGroups(w http.ResponseWriter, r *http.Request, params ListGroupsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /groups)
func (_ Unimplemented) CreateGroup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /groups/{id})
func (_ Unimplemented) DeleteGroup(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /groups/{id})
func (_ Unimplemented) GetGroup(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /groups/{id})
func (_ Unimplemented) UpdateGroup(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /machines)
func (_ Unimplemented) ListMachines(w http.ResponseWriter, r *http.Request, params ListMachinesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /machines/{id})
func (_ Unimplemented) DeleteMachine(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /machines/{id})
func (_ Unimplemented) GetMachine(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /rules)
func (_ Unimplemented) ListRules(w http.ResponseWriter, r *http.Request, params ListRulesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /rules)
func (_ Unimplemented) CreateRule(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /rules/{id})
func (_ Unimplemented) DeleteRule(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /rules/{id})
func (_ Unimplemented) GetRule(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /rules/{id})
func (_ Unimplemented) UpdateRule(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /users/{id})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListExecutables operation middleware
func (siw *ServerInterfaceWrapper) ListExecutables(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExecutablesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExecutables(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecutable operation middleware
func (siw *ServerInterfaceWrapper) GetExecutable(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecutable(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListExecutionEvents operation middleware
func (siw *ServerInterfaceWrapper) ListExecutionEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExecutionEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "machine_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "machine_id", r.URL.Query(), &params.MachineId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "machine_id", Err: err})
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", r.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// ------------- Optional query parameter "executable_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "executable_id", r.URL.Query(), &params.ExecutableId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "executable_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExecutionEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteExecutionEvent operation middleware
func (siw *ServerInterfaceWrapper) DeleteExecutionEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteExecutionEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecutionEvent operation middleware
func (siw *ServerInterfaceWrapper) GetExecutionEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecutionEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFileAccessEvents operation middleware
func (siw *ServerInterfaceWrapper) ListFileAccessEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFileAccessEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "machine_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "machine_id", r.URL.Query(), &params.MachineId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "machine_id", Err: err})
		return
	}

	// ------------- Optional query parameter "executable_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "executable_id", r.URL.Query(), &params.ExecutableId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "executable_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFileAccessEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFileAccessEvent operation middleware
func (siw *ServerInterfaceWrapper) DeleteFileAccessEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFileAccessEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFileAccessEvent operation middleware
func (siw *ServerInterfaceWrapper) GetFileAccessEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFileAccessEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGroupMemberships operation middleware
func (siw *ServerInterfaceWrapper) ListGroupMemberships(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupMembershipsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "group_id", r.URL.Query(), &params.GroupId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_id", Err: err})
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", r.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// ------------- Optional query parameter "machine_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "machine_id", r.URL.Query(), &params.MachineId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "machine_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroupMemberships(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGroupMembership operation middleware
func (siw *ServerInterfaceWrapper) CreateGroupMembership(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGroupMembership(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGroupMembership operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroupMembership(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GroupMembershipId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGroupMembership(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroupMembership operation middleware
func (siw *ServerInterfaceWrapper) GetGroupMembership(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GroupMembershipId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroupMembership(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroups(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateGroup(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGroup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMachines operation middleware
func (siw *ServerInterfaceWrapper) ListMachines(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMachinesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", r.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMachines(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMachine operation middleware
func (siw *ServerInterfaceWrapper) DeleteMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMachine(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMachine operation middleware
func (siw *ServerInterfaceWrapper) GetMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMachine(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRules operation middleware
func (siw *ServerInterfaceWrapper) ListRules(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRulesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRules(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRule operation middleware
func (siw *ServerInterfaceWrapper) CreateRule(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRule operation middleware
func (siw *ServerInterfaceWrapper) DeleteRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRule operation middleware
func (siw *ServerInterfaceWrapper) GetRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRule operation middleware
func (siw *ServerInterfaceWrapper) UpdateRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/executables", wrapper.ListExecutables)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/executables/{id}", wrapper.GetExecutable)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/execution-events", wrapper.ListExecutionEvents)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/execution-events/{id}", wrapper.DeleteExecutionEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/execution-events/{id}", wrapper.GetExecutionEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/file-access-events", wrapper.ListFileAccessEvents)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/file-access-events/{id}", wrapper.DeleteFileAccessEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/file-access-events/{id}", wrapper.GetFileAccessEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/group-memberships", wrapper.ListGroupMemberships)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/group-memberships", wrapper.CreateGroupMembership)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/group-memberships/{id}", wrapper.DeleteGroupMembership)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/group-memberships/{id}", wrapper.GetGroupMembership)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/groups", wrapper.ListGroups)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/groups", wrapper.CreateGroup)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/groups/{id}", wrapper.DeleteGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/groups/{id}", wrapper.GetGroup)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/groups/{id}", wrapper.UpdateGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/machines", wrapper.ListMachines)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/machines/{id}", wrapper.DeleteMachine)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/machines/{id}", wrapper.GetMachine)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rules", wrapper.ListRules)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/rules", wrapper.CreateRule)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/rules/{id}", wrapper.DeleteRule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rules/{id}", wrapper.GetRule)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/rules/{id}", wrapper.UpdateRule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}", wrapper.GetUser)
	})

	return r
}
