// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package httpapi

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionAuthScopes = "sessionAuth.Scopes"
)

// Defines values for EventDecision.
const (
	EventDecisionAllowBinary      EventDecision = "allow_binary"
	EventDecisionAllowCdHash      EventDecision = "allow_cd_hash"
	EventDecisionAllowCertificate EventDecision = "allow_certificate"
	EventDecisionAllowScope       EventDecision = "allow_scope"
	EventDecisionAllowSigningId   EventDecision = "allow_signing_id"
	EventDecisionAllowTeamId      EventDecision = "allow_team_id"
	EventDecisionAllowUnknown     EventDecision = "allow_unknown"
	EventDecisionBlockBinary      EventDecision = "block_binary"
	EventDecisionBlockCdHash      EventDecision = "block_cd_hash"
	EventDecisionBlockCertificate EventDecision = "block_certificate"
	EventDecisionBlockScope       EventDecision = "block_scope"
	EventDecisionBlockSigningId   EventDecision = "block_signing_id"
	EventDecisionBlockTeamId      EventDecision = "block_team_id"
	EventDecisionBlockUnknown     EventDecision = "block_unknown"
	EventDecisionBundleBinary     EventDecision = "bundle_binary"
	EventDecisionUnknown          EventDecision = "unknown"
)

// Valid indicates whether the value is a known member of the EventDecision enum.
func (e EventDecision) Valid() bool {
	switch e {
	case EventDecisionAllowBinary:
		return true
	case EventDecisionAllowCdHash:
		return true
	case EventDecisionAllowCertificate:
		return true
	case EventDecisionAllowScope:
		return true
	case EventDecisionAllowSigningId:
		return true
	case EventDecisionAllowTeamId:
		return true
	case EventDecisionAllowUnknown:
		return true
	case EventDecisionBlockBinary:
		return true
	case EventDecisionBlockCdHash:
		return true
	case EventDecisionBlockCertificate:
		return true
	case EventDecisionBlockScope:
		return true
	case EventDecisionBlockSigningId:
		return true
	case EventDecisionBlockTeamId:
		return true
	case EventDecisionBlockUnknown:
		return true
	case EventDecisionBundleBinary:
		return true
	case EventDecisionUnknown:
		return true
	default:
		return false
	}
}

// Defines values for ExecutableSource.
const (
	Event   ExecutableSource = "event"
	Process ExecutableSource = "process"
)

// Valid indicates whether the value is a known member of the ExecutableSource enum.
func (e ExecutableSource) Valid() bool {
	switch e {
	case Event:
		return true
	case Process:
		return true
	default:
		return false
	}
}

// Defines values for FileAccessDecision.
const (
	FileAccessDecisionAuditOnly              FileAccessDecision = "audit_only"
	FileAccessDecisionDenied                 FileAccessDecision = "denied"
	FileAccessDecisionDeniedInvalidSignature FileAccessDecision = "denied_invalid_signature"
	FileAccessDecisionUnknown                FileAccessDecision = "unknown"
)

// Valid indicates whether the value is a known member of the FileAccessDecision enum.
func (e FileAccessDecision) Valid() bool {
	switch e {
	case FileAccessDecisionAuditOnly:
		return true
	case FileAccessDecisionDenied:
		return true
	case FileAccessDecisionDeniedInvalidSignature:
		return true
	case FileAccessDecisionUnknown:
		return true
	default:
		return false
	}
}

// Defines values for GroupMembershipKind.
const (
	Actual    GroupMembershipKind = "actual"
	Effective GroupMembershipKind = "effective"
)

// Valid indicates whether the value is a known member of the GroupMembershipKind enum.
func (e GroupMembershipKind) Valid() bool {
	switch e {
	case Actual:
		return true
	case Effective:
		return true
	default:
		return false
	}
}

// Defines values for MemberKind.
const (
	MemberKindMachine MemberKind = "machine"
	MemberKindUser    MemberKind = "user"
)

// Valid indicates whether the value is a known member of the MemberKind enum.
func (e MemberKind) Valid() bool {
	switch e {
	case MemberKindMachine:
		return true
	case MemberKindUser:
		return true
	default:
		return false
	}
}

// Defines values for RulePolicy.
const (
	Allowlist       RulePolicy = "allowlist"
	Blocklist       RulePolicy = "blocklist"
	Cel             RulePolicy = "cel"
	SilentBlocklist RulePolicy = "silent_blocklist"
)

// Valid indicates whether the value is a known member of the RulePolicy enum.
func (e RulePolicy) Valid() bool {
	switch e {
	case Allowlist:
		return true
	case Blocklist:
		return true
	case Cel:
		return true
	case SilentBlocklist:
		return true
	default:
		return false
	}
}

// Defines values for RuleTargetAssignment.
const (
	Exclude RuleTargetAssignment = "exclude"
	Include RuleTargetAssignment = "include"
)

// Valid indicates whether the value is a known member of the RuleTargetAssignment enum.
func (e RuleTargetAssignment) Valid() bool {
	switch e {
	case Exclude:
		return true
	case Include:
		return true
	default:
		return false
	}
}

// Defines values for RuleTargetSubjectKind.
const (
	RuleTargetSubjectKindGroup RuleTargetSubjectKind = "group"
)

// Valid indicates whether the value is a known member of the RuleTargetSubjectKind enum.
func (e RuleTargetSubjectKind) Valid() bool {
	switch e {
	case RuleTargetSubjectKindGroup:
		return true
	default:
		return false
	}
}

// Defines values for RuleType.
const (
	Binary      RuleType = "binary"
	CdHash      RuleType = "cd_hash"
	Certificate RuleType = "certificate"
	SigningId   RuleType = "signing_id"
	TeamId      RuleType = "team_id"
)

// Valid indicates whether the value is a known member of the RuleType enum.
func (e RuleType) Valid() bool {
	switch e {
	case Binary:
		return true
	case CdHash:
		return true
	case Certificate:
		return true
	case SigningId:
		return true
	case TeamId:
		return true
	default:
		return false
	}
}

// Defines values for Source.
const (
	Entra Source = "entra"
	Local Source = "local"
)

// Valid indicates whether the value is a known member of the Source enum.
func (e Source) Valid() bool {
	switch e {
	case Entra:
		return true
	case Local:
		return true
	default:
		return false
	}
}

// Defines values for Order.
const (
	OrderAsc  Order = "asc"
	OrderDesc Order = "desc"
)

// Valid indicates whether the value is a known member of the Order enum.
func (e Order) Valid() bool {
	switch e {
	case OrderAsc:
		return true
	case OrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListExecutablesParamsOrder.
const (
	ListExecutablesParamsOrderAsc  ListExecutablesParamsOrder = "asc"
	ListExecutablesParamsOrderDesc ListExecutablesParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListExecutablesParamsOrder enum.
func (e ListExecutablesParamsOrder) Valid() bool {
	switch e {
	case ListExecutablesParamsOrderAsc:
		return true
	case ListExecutablesParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListExecutionEventsParamsOrder.
const (
	ListExecutionEventsParamsOrderAsc  ListExecutionEventsParamsOrder = "asc"
	ListExecutionEventsParamsOrderDesc ListExecutionEventsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListExecutionEventsParamsOrder enum.
func (e ListExecutionEventsParamsOrder) Valid() bool {
	switch e {
	case ListExecutionEventsParamsOrderAsc:
		return true
	case ListExecutionEventsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListFileAccessEventsParamsOrder.
const (
	ListFileAccessEventsParamsOrderAsc  ListFileAccessEventsParamsOrder = "asc"
	ListFileAccessEventsParamsOrderDesc ListFileAccessEventsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListFileAccessEventsParamsOrder enum.
func (e ListFileAccessEventsParamsOrder) Valid() bool {
	switch e {
	case ListFileAccessEventsParamsOrderAsc:
		return true
	case ListFileAccessEventsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListGroupMembershipsParamsOrder.
const (
	ListGroupMembershipsParamsOrderAsc  ListGroupMembershipsParamsOrder = "asc"
	ListGroupMembershipsParamsOrderDesc ListGroupMembershipsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListGroupMembershipsParamsOrder enum.
func (e ListGroupMembershipsParamsOrder) Valid() bool {
	switch e {
	case ListGroupMembershipsParamsOrderAsc:
		return true
	case ListGroupMembershipsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListGroupsParamsOrder.
const (
	ListGroupsParamsOrderAsc  ListGroupsParamsOrder = "asc"
	ListGroupsParamsOrderDesc ListGroupsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListGroupsParamsOrder enum.
func (e ListGroupsParamsOrder) Valid() bool {
	switch e {
	case ListGroupsParamsOrderAsc:
		return true
	case ListGroupsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListMachinesParamsOrder.
const (
	ListMachinesParamsOrderAsc  ListMachinesParamsOrder = "asc"
	ListMachinesParamsOrderDesc ListMachinesParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListMachinesParamsOrder enum.
func (e ListMachinesParamsOrder) Valid() bool {
	switch e {
	case ListMachinesParamsOrderAsc:
		return true
	case ListMachinesParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListRuleTargetsParamsOrder.
const (
	ListRuleTargetsParamsOrderAsc  ListRuleTargetsParamsOrder = "asc"
	ListRuleTargetsParamsOrderDesc ListRuleTargetsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListRuleTargetsParamsOrder enum.
func (e ListRuleTargetsParamsOrder) Valid() bool {
	switch e {
	case ListRuleTargetsParamsOrderAsc:
		return true
	case ListRuleTargetsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListRulesParamsOrder.
const (
	ListRulesParamsOrderAsc  ListRulesParamsOrder = "asc"
	ListRulesParamsOrderDesc ListRulesParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListRulesParamsOrder enum.
func (e ListRulesParamsOrder) Valid() bool {
	switch e {
	case ListRulesParamsOrderAsc:
		return true
	case ListRulesParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListUsersParamsOrder.
const (
	ListUsersParamsOrderAsc  ListUsersParamsOrder = "asc"
	ListUsersParamsOrderDesc ListUsersParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListUsersParamsOrder enum.
func (e ListUsersParamsOrder) Valid() bool {
	switch e {
	case ListUsersParamsOrderAsc:
		return true
	case ListUsersParamsOrderDesc:
		return true
	default:
		return false
	}
}

// EventDecision defines model for EventDecision.
type EventDecision string

// Executable defines model for Executable.
type Executable struct {
	Cdhash         string                 `json:"cdhash"`
	CreatedAt      time.Time              `json:"created_at"`
	Entitlements   map[string]interface{} `json:"entitlements"`
	FileBundleId   string                 `json:"file_bundle_id"`
	FileBundlePath string                 `json:"file_bundle_path"`
	FileName       string                 `json:"file_name"`
	FilePath       string                 `json:"file_path"`
	FileSha256     string                 `json:"file_sha256"`
	Id             openapi_types.UUID     `json:"id"`
	SigningChain   []SigningChainEntry    `json:"signing_chain"`
	SigningId      string                 `json:"signing_id"`
	Source         ExecutableSource       `json:"source"`
	TeamId         string                 `json:"team_id"`
}

// ExecutableListResponse defines model for ExecutableListResponse.
type ExecutableListResponse struct {
	Rows  []ExecutableSummary `json:"rows"`
	Total int32               `json:"total"`
}

// ExecutableSource defines model for ExecutableSource.
type ExecutableSource string

// ExecutableSummary defines model for ExecutableSummary.
type ExecutableSummary struct {
	Cdhash         string             `json:"cdhash"`
	CreatedAt      time.Time          `json:"created_at"`
	FileBundleId   string             `json:"file_bundle_id"`
	FileBundlePath string             `json:"file_bundle_path"`
	FileName       string             `json:"file_name"`
	FilePath       string             `json:"file_path"`
	FileSha256     string             `json:"file_sha256"`
	Id             openapi_types.UUID `json:"id"`
	SigningId      string             `json:"signing_id"`
	Source         ExecutableSource   `json:"source"`
	TeamId         string             `json:"team_id"`
}

// ExecutionEvent defines model for ExecutionEvent.
type ExecutionEvent struct {
	Cdhash          string                 `json:"cdhash"`
	CreatedAt       time.Time              `json:"created_at"`
	CurrentSessions []string               `json:"current_sessions"`
	Decision        EventDecision          `json:"decision"`
	Entitlements    map[string]interface{} `json:"entitlements"`
	ExecutableId    openapi_types.UUID     `json:"executable_id"`
	ExecutingUser   string                 `json:"executing_user"`
	FileBundleId    string                 `json:"file_bundle_id"`
	FileBundlePath  string                 `json:"file_bundle_path"`
	FileName        string                 `json:"file_name"`
	FilePath        string                 `json:"file_path"`
	FileSha256      string                 `json:"file_sha256"`
	Id              openapi_types.UUID     `json:"id"`
	LoggedInUsers   []string               `json:"logged_in_users"`
	MachineId       openapi_types.UUID     `json:"machine_id"`
	OccurredAt      *time.Time             `json:"occurred_at,omitempty"`
	SigningChain    []SigningChainEntry    `json:"signing_chain"`
	SigningId       string                 `json:"signing_id"`
	TeamId          string                 `json:"team_id"`
}

// ExecutionEventListResponse defines model for ExecutionEventListResponse.
type ExecutionEventListResponse struct {
	Rows  []ExecutionEventSummary `json:"rows"`
	Total int32                   `json:"total"`
}

// ExecutionEventSummary defines model for ExecutionEventSummary.
type ExecutionEventSummary struct {
	CreatedAt    time.Time          `json:"created_at"`
	Decision     EventDecision      `json:"decision"`
	ExecutableId openapi_types.UUID `json:"executable_id"`
	FileName     string             `json:"file_name"`
	FilePath     string             `json:"file_path"`
	Id           openapi_types.UUID `json:"id"`
	MachineId    openapi_types.UUID `json:"machine_id"`
	OccurredAt   *time.Time         `json:"occurred_at,omitempty"`
	SigningId    string             `json:"signing_id"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Code    *string `json:"code,omitempty"`
	Field   string  `json:"field"`
	Message string  `json:"message"`
}

// FileAccessDecision defines model for FileAccessDecision.
type FileAccessDecision string

// FileAccessEvent defines model for FileAccessEvent.
type FileAccessEvent struct {
	Cdhash       string                   `json:"cdhash"`
	CreatedAt    time.Time                `json:"created_at"`
	Decision     FileAccessDecision       `json:"decision"`
	ExecutableId *openapi_types.UUID      `json:"executable_id,omitempty"`
	FileName     string                   `json:"file_name"`
	FileSha256   string                   `json:"file_sha256"`
	Id           openapi_types.UUID       `json:"id"`
	MachineId    openapi_types.UUID       `json:"machine_id"`
	OccurredAt   *time.Time               `json:"occurred_at,omitempty"`
	ProcessChain []FileAccessEventProcess `json:"process_chain"`
	RuleName     string                   `json:"rule_name"`
	RuleVersion  string                   `json:"rule_version"`
	SigningId    string                   `json:"signing_id"`
	Target       string                   `json:"target"`
	TeamId       string                   `json:"team_id"`
}

// FileAccessEventListResponse defines model for FileAccessEventListResponse.
type FileAccessEventListResponse struct {
	Rows  []FileAccessEventSummary `json:"rows"`
	Total int32                    `json:"total"`
}

// FileAccessEventProcess defines model for FileAccessEventProcess.
type FileAccessEventProcess struct {
	ExecutableId openapi_types.UUID `json:"executable_id"`
	FileName     string             `json:"file_name"`
	FilePath     string             `json:"file_path"`
	Pid          int32              `json:"pid"`
}

// FileAccessEventSummary defines model for FileAccessEventSummary.
type FileAccessEventSummary struct {
	Cdhash       string              `json:"cdhash"`
	CreatedAt    time.Time           `json:"created_at"`
	Decision     FileAccessDecision  `json:"decision"`
	ExecutableId *openapi_types.UUID `json:"executable_id"`
	FileName     string              `json:"file_name"`
	FileSha256   string              `json:"file_sha256"`
	Id           openapi_types.UUID  `json:"id"`
	MachineId    openapi_types.UUID  `json:"machine_id"`
	OccurredAt   *time.Time          `json:"occurred_at,omitempty"`
	RuleName     string              `json:"rule_name"`
	SigningId    string              `json:"signing_id"`
	Target       string              `json:"target"`
	TeamId       string              `json:"team_id"`
}

// Group defines model for Group.
type Group struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	MemberCount int32              `json:"member_count"`
	Name        string             `json:"name"`
	Source      Source             `json:"source"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// GroupCreateRequest defines model for GroupCreateRequest.
type GroupCreateRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// GroupListResponse defines model for GroupListResponse.
type GroupListResponse struct {
	Rows  []Group `json:"rows"`
	Total int32   `json:"total"`
}

// GroupMembership defines model for GroupMembership.
type GroupMembership struct {
	CreatedAt time.Time             `json:"created_at"`
	Group     GroupMembershipGroup  `json:"group"`
	Id        string                `json:"id"`
	Kind      GroupMembershipKind   `json:"kind"`
	Member    GroupMembershipMember `json:"member"`
	UpdatedAt time.Time             `json:"updated_at"`
}

// GroupMembershipCreateRequest defines model for GroupMembershipCreateRequest.
type GroupMembershipCreateRequest struct {
	GroupId    openapi_types.UUID `json:"group_id"`
	MemberId   openapi_types.UUID `json:"member_id"`
	MemberKind MemberKind         `json:"member_kind"`
}

// GroupMembershipGroup defines model for GroupMembershipGroup.
type GroupMembershipGroup struct {
	Id     openapi_types.UUID `json:"id"`
	Name   string             `json:"name"`
	Source Source             `json:"source"`
}

// GroupMembershipKind defines model for GroupMembershipKind.
type GroupMembershipKind string

// GroupMembershipListResponse defines model for GroupMembershipListResponse.
type GroupMembershipListResponse struct {
	Rows  []GroupMembership `json:"rows"`
	Total int32             `json:"total"`
}

// GroupMembershipMember defines model for GroupMembershipMember.
type GroupMembershipMember struct {
	Id   openapi_types.UUID `json:"id"`
	Kind MemberKind         `json:"kind"`
	Name *string            `json:"name,omitempty"`
}

// GroupPatchRequest defines model for GroupPatchRequest.
type GroupPatchRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// Machine defines model for Machine.
type Machine struct {
	CreatedAt        time.Time           `json:"created_at"`
	Hostname         string              `json:"hostname"`
	Id               openapi_types.UUID  `json:"id"`
	LastSeenAt       time.Time           `json:"last_seen_at"`
	ModelIdentifier  string              `json:"model_identifier"`
	OsBuild          string              `json:"os_build"`
	OsVersion        string              `json:"os_version"`
	PrimaryUser      string              `json:"primary_user"`
	PrimaryUserId    *openapi_types.UUID `json:"primary_user_id,omitempty"`
	RequestCleanSync bool                `json:"request_clean_sync"`
	SantaVersion     string              `json:"santa_version"`
	SerialNumber     string              `json:"serial_number"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

// MachineListResponse defines model for MachineListResponse.
type MachineListResponse struct {
	Rows  []MachineSummary `json:"rows"`
	Total int32            `json:"total"`
}

// MachineSummary defines model for MachineSummary.
type MachineSummary struct {
	CreatedAt       time.Time           `json:"created_at"`
	Hostname        string              `json:"hostname"`
	Id              openapi_types.UUID  `json:"id"`
	LastSeenAt      time.Time           `json:"last_seen_at"`
	ModelIdentifier string              `json:"model_identifier"`
	OsVersion       string              `json:"os_version"`
	PrimaryUser     string              `json:"primary_user"`
	PrimaryUserId   *openapi_types.UUID `json:"primary_user_id,omitempty"`
	SantaVersion    string              `json:"santa_version"`
	SerialNumber    string              `json:"serial_number"`
	UpdatedAt       time.Time           `json:"updated_at"`
}

// MemberKind defines model for MemberKind.
type MemberKind string

// Problem defines model for Problem.
type Problem struct {
	Code        string        `json:"code"`
	Detail      string        `json:"detail"`
	FieldErrors *[]FieldError `json:"field_errors,omitempty"`
	Status      int32         `json:"status"`
	Title       string        `json:"title"`
	Type        string        `json:"type"`
}

// Rule defines model for Rule.
type Rule struct {
	CreatedAt     time.Time          `json:"created_at"`
	CustomMessage string             `json:"custom_message"`
	CustomUrl     string             `json:"custom_url"`
	Description   string             `json:"description"`
	Enabled       bool               `json:"enabled"`
	Id            openapi_types.UUID `json:"id"`
	Identifier    string             `json:"identifier"`
	Name          string             `json:"name"`
	RuleType      RuleType           `json:"rule_type"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

// RuleCreateRequest defines model for RuleCreateRequest.
type RuleCreateRequest struct {
	CustomMessage *string `json:"custom_message,omitempty"`
	CustomUrl     *string `json:"custom_url,omitempty"`
	Description   *string `json:"description,omitempty"`

	// Enabled Default true when omitted.
	Enabled    *bool    `json:"enabled,omitempty"`
	Identifier string   `json:"identifier"`
	Name       string   `json:"name"`
	RuleType   RuleType `json:"rule_type"`
}

// RuleListResponse defines model for RuleListResponse.
type RuleListResponse struct {
	Rows  []RuleSummary `json:"rows"`
	Total int32         `json:"total"`
}

// RulePatchRequest defines model for RulePatchRequest.
type RulePatchRequest struct {
	CustomMessage *string   `json:"custom_message,omitempty"`
	CustomUrl     *string   `json:"custom_url,omitempty"`
	Description   *string   `json:"description,omitempty"`
	Enabled       *bool     `json:"enabled,omitempty"`
	Identifier    *string   `json:"identifier,omitempty"`
	Name          *string   `json:"name,omitempty"`
	RuleType      *RuleType `json:"rule_type,omitempty"`
}

// RulePolicy defines model for RulePolicy.
type RulePolicy string

// RuleSummary defines model for RuleSummary.
type RuleSummary struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description string             `json:"description"`
	Enabled     bool               `json:"enabled"`
	Id          openapi_types.UUID `json:"id"`
	Identifier  string             `json:"identifier"`
	Name        string             `json:"name"`
	RuleType    RuleType           `json:"rule_type"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// RuleTarget defines model for RuleTarget.
type RuleTarget struct {
	Assignment    RuleTargetAssignment  `json:"assignment"`
	CelExpression *string               `json:"cel_expression,omitempty"`
	CreatedAt     time.Time             `json:"created_at"`
	Id            openapi_types.UUID    `json:"id"`
	Policy        *RulePolicy           `json:"policy,omitempty"`
	Priority      *int32                `json:"priority,omitempty"`
	RuleId        openapi_types.UUID    `json:"rule_id"`
	SubjectId     openapi_types.UUID    `json:"subject_id"`
	SubjectKind   RuleTargetSubjectKind `json:"subject_kind"`
	UpdatedAt     time.Time             `json:"updated_at"`
}

// RuleTargetAssignment defines model for RuleTargetAssignment.
type RuleTargetAssignment string

// RuleTargetCreateRequest defines model for RuleTargetCreateRequest.
type RuleTargetCreateRequest struct {
	Assignment    RuleTargetAssignment `json:"assignment"`
	CelExpression *string              `json:"cel_expression,omitempty"`
	Policy        *RulePolicy          `json:"policy,omitempty"`
	Priority      *int32               `json:"priority,omitempty"`
	RuleId        openapi_types.UUID   `json:"rule_id"`
	SubjectId     openapi_types.UUID   `json:"subject_id"`
}

// RuleTargetListResponse defines model for RuleTargetListResponse.
type RuleTargetListResponse struct {
	Rows  []RuleTargetSummary `json:"rows"`
	Total int32               `json:"total"`
}

// RuleTargetPatchRequest defines model for RuleTargetPatchRequest.
type RuleTargetPatchRequest struct {
	Assignment    *RuleTargetAssignment `json:"assignment,omitempty"`
	CelExpression *string               `json:"cel_expression,omitempty"`
	Policy        *RulePolicy           `json:"policy,omitempty"`
	Priority      *int32                `json:"priority,omitempty"`
	SubjectId     *openapi_types.UUID   `json:"subject_id,omitempty"`
}

// RuleTargetSubjectKind defines model for RuleTargetSubjectKind.
type RuleTargetSubjectKind string

// RuleTargetSummary defines model for RuleTargetSummary.
type RuleTargetSummary struct {
	Assignment  RuleTargetAssignment  `json:"assignment"`
	CreatedAt   time.Time             `json:"created_at"`
	Id          openapi_types.UUID    `json:"id"`
	Policy      *RulePolicy           `json:"policy,omitempty"`
	Priority    *int32                `json:"priority,omitempty"`
	RuleId      openapi_types.UUID    `json:"rule_id"`
	SubjectId   openapi_types.UUID    `json:"subject_id"`
	SubjectKind RuleTargetSubjectKind `json:"subject_kind"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

// RuleType defines model for RuleType.
type RuleType string

// SigningChainEntry defines model for SigningChainEntry.
type SigningChainEntry struct {
	CommonName         string    `json:"common_name"`
	Organization       string    `json:"organization"`
	OrganizationalUnit string    `json:"organizational_unit"`
	Sha256             string    `json:"sha256"`
	ValidFrom          time.Time `json:"valid_from"`
	ValidUntil         time.Time `json:"valid_until"`
}

// Source defines model for Source.
type Source string

// User defines model for User.
type User struct {
	CreatedAt   time.Time          `json:"created_at"`
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	Source      Source             `json:"source"`
	UpdatedAt   time.Time          `json:"updated_at"`
	Upn         string             `json:"upn"`
}

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	Rows  []User `json:"rows"`
	Total int32  `json:"total"`
}

// ExecutableIdFilter defines model for ExecutableIdFilter.
type ExecutableIdFilter = openapi_types.UUID

// GroupIdFilter defines model for GroupIdFilter.
type GroupIdFilter = openapi_types.UUID

// GroupMembershipId defines model for GroupMembershipId.
type GroupMembershipId = openapi_types.UUID

// Id defines model for Id.
type Id = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int32

// MachineIdFilter defines model for MachineIdFilter.
type MachineIdFilter = openapi_types.UUID

// Offset defines model for Offset.
type Offset = int32

// Order defines model for Order.
type Order string

// RuleIdFilter defines model for RuleIdFilter.
type RuleIdFilter = openapi_types.UUID

// RulePolicyFilter defines model for RulePolicyFilter.
type RulePolicyFilter = RulePolicy

// RuleTargetAssignmentFilter defines model for RuleTargetAssignmentFilter.
type RuleTargetAssignmentFilter = RuleTargetAssignment

// Search defines model for Search.
type Search = string

// Sort defines model for Sort.
type Sort = string

// SubjectIdFilter defines model for SubjectIdFilter.
type SubjectIdFilter = openapi_types.UUID

// SubjectKindFilter defines model for SubjectKindFilter.
type SubjectKindFilter = RuleTargetSubjectKind

// UserIdFilter defines model for UserIdFilter.
type UserIdFilter = openapi_types.UUID

// NotFound defines model for NotFound.
type NotFound = Problem

// ListExecutablesParams defines parameters for ListExecutables.
type ListExecutablesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort  *Sort                       `form:"sort,omitempty" json:"sort,omitempty"`
	Order *ListExecutablesParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// ListExecutablesParamsOrder defines parameters for ListExecutables.
type ListExecutablesParamsOrder string

// ListExecutionEventsParams defines parameters for ListExecutionEvents.
type ListExecutionEventsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort         *Sort                           `form:"sort,omitempty" json:"sort,omitempty"`
	Order        *ListExecutionEventsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	MachineId    *MachineIdFilter                `form:"machine_id,omitempty" json:"machine_id,omitempty"`
	UserId       *UserIdFilter                   `form:"user_id,omitempty" json:"user_id,omitempty"`
	ExecutableId *ExecutableIdFilter             `form:"executable_id,omitempty" json:"executable_id,omitempty"`
}

// ListExecutionEventsParamsOrder defines parameters for ListExecutionEvents.
type ListExecutionEventsParamsOrder string

// ListFileAccessEventsParams defines parameters for ListFileAccessEvents.
type ListFileAccessEventsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort         *Sort                            `form:"sort,omitempty" json:"sort,omitempty"`
	Order        *ListFileAccessEventsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	MachineId    *MachineIdFilter                 `form:"machine_id,omitempty" json:"machine_id,omitempty"`
	ExecutableId *ExecutableIdFilter              `form:"executable_id,omitempty" json:"executable_id,omitempty"`
}

// ListFileAccessEventsParamsOrder defines parameters for ListFileAccessEvents.
type ListFileAccessEventsParamsOrder string

// ListGroupMembershipsParams defines parameters for ListGroupMemberships.
type ListGroupMembershipsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort      *Sort                            `form:"sort,omitempty" json:"sort,omitempty"`
	Order     *ListGroupMembershipsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	GroupId   *GroupIdFilter                   `form:"group_id,omitempty" json:"group_id,omitempty"`
	UserId    *UserIdFilter                    `form:"user_id,omitempty" json:"user_id,omitempty"`
	MachineId *MachineIdFilter                 `form:"machine_id,omitempty" json:"machine_id,omitempty"`
}

// ListGroupMembershipsParamsOrder defines parameters for ListGroupMemberships.
type ListGroupMembershipsParamsOrder string

// ListGroupsParams defines parameters for ListGroups.
type ListGroupsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort  *Sort                  `form:"sort,omitempty" json:"sort,omitempty"`
	Order *ListGroupsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// ListGroupsParamsOrder defines parameters for ListGroups.
type ListGroupsParamsOrder string

// ListMachinesParams defines parameters for ListMachines.
type ListMachinesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort   *Sort                    `form:"sort,omitempty" json:"sort,omitempty"`
	Order  *ListMachinesParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	UserId *UserIdFilter            `form:"user_id,omitempty" json:"user_id,omitempty"`
}

// ListMachinesParamsOrder defines parameters for ListMachines.
type ListMachinesParamsOrder string

// ListRuleTargetsParams defines parameters for ListRuleTargets.
type ListRuleTargetsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort        *Sort                       `form:"sort,omitempty" json:"sort,omitempty"`
	Order       *ListRuleTargetsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	RuleId      *RuleIdFilter               `form:"rule_id,omitempty" json:"rule_id,omitempty"`
	SubjectKind *SubjectKindFilter          `form:"subject_kind,omitempty" json:"subject_kind,omitempty"`
	SubjectId   *SubjectIdFilter            `form:"subject_id,omitempty" json:"subject_id,omitempty"`
	Assignment  *RuleTargetAssignmentFilter `form:"assignment,omitempty" json:"assignment,omitempty"`
	Policy      *RulePolicyFilter           `form:"policy,omitempty" json:"policy,omitempty"`
}

// ListRuleTargetsParamsOrder defines parameters for ListRuleTargets.
type ListRuleTargetsParamsOrder string

// ListRulesParams defines parameters for ListRules.
type ListRulesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort  *Sort                 `form:"sort,omitempty" json:"sort,omitempty"`
	Order *ListRulesParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// ListRulesParamsOrder defines parameters for ListRules.
type ListRulesParamsOrder string

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Sort field name.
	Sort  *Sort                 `form:"sort,omitempty" json:"sort,omitempty"`
	Order *ListUsersParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// ListUsersParamsOrder defines parameters for ListUsers.
type ListUsersParamsOrder string

// CreateGroupMembershipJSONRequestBody defines body for CreateGroupMembership for application/json ContentType.
type CreateGroupMembershipJSONRequestBody = GroupMembershipCreateRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = GroupCreateRequest

// PatchGroupJSONRequestBody defines body for PatchGroup for application/json ContentType.
type PatchGroupJSONRequestBody = GroupPatchRequest

// CreateRuleTargetJSONRequestBody defines body for CreateRuleTarget for application/json ContentType.
type CreateRuleTargetJSONRequestBody = RuleTargetCreateRequest

// PatchRuleTargetJSONRequestBody defines body for PatchRuleTarget for application/json ContentType.
type PatchRuleTargetJSONRequestBody = RuleTargetPatchRequest

// CreateRuleJSONRequestBody defines body for CreateRule for application/json ContentType.
type CreateRuleJSONRequestBody = RuleCreateRequest

// PatchRuleJSONRequestBody defines body for PatchRule for application/json ContentType.
type PatchRuleJSONRequestBody = RulePatchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /executables)
	ListExecutables(w http.ResponseWriter, r *http.Request, params ListExecutablesParams)

	// (GET /executables/{id})
	GetExecutable(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /execution-events)
	ListExecutionEvents(w http.ResponseWriter, r *http.Request, params ListExecutionEventsParams)

	// (DELETE /execution-events/{id})
	DeleteExecutionEvent(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /execution-events/{id})
	GetExecutionEvent(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /file-access-events)
	ListFileAccessEvents(w http.ResponseWriter, r *http.Request, params ListFileAccessEventsParams)

	// (DELETE /file-access-events/{id})
	DeleteFileAccessEvent(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /file-access-events/{id})
	GetFileAccessEvent(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /group-memberships)
	ListGroupMemberships(w http.ResponseWriter, r *http.Request, params ListGroupMembershipsParams)

	// (POST /group-memberships)
	CreateGroupMembership(w http.ResponseWriter, r *http.Request)

	// (DELETE /group-memberships/{id})
	DeleteGroupMembership(w http.ResponseWriter, r *http.Request, id GroupMembershipId)

	// (GET /group-memberships/{id})
	GetGroupMembership(w http.ResponseWriter, r *http.Request, id GroupMembershipId)

	// (GET /groups)
	ListGroups(w http.ResponseWriter, r *http.Request, params ListGroupsParams)

	// (POST /groups)
	CreateGroup(w http.ResponseWriter, r *http.Request)

	// (DELETE /groups/{id})
	DeleteGroup(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /groups/{id})
	GetGroup(w http.ResponseWriter, r *http.Request, id Id)

	// (PATCH /groups/{id})
	PatchGroup(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /machines)
	ListMachines(w http.ResponseWriter, r *http.Request, params ListMachinesParams)

	// (DELETE /machines/{id})
	DeleteMachine(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /machines/{id})
	GetMachine(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /rule-targets)
	ListRuleTargets(w http.ResponseWriter, r *http.Request, params ListRuleTargetsParams)

	// (POST /rule-targets)
	CreateRuleTarget(w http.ResponseWriter, r *http.Request)

	// (DELETE /rule-targets/{id})
	DeleteRuleTarget(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /rule-targets/{id})
	GetRuleTarget(w http.ResponseWriter, r *http.Request, id Id)

	// (PATCH /rule-targets/{id})
	PatchRuleTarget(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /rules)
	ListRules(w http.ResponseWriter, r *http.Request, params ListRulesParams)

	// (POST /rules)
	CreateRule(w http.ResponseWriter, r *http.Request)

	// (DELETE /rules/{id})
	DeleteRule(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /rules/{id})
	GetRule(w http.ResponseWriter, r *http.Request, id Id)

	// (PATCH /rules/{id})
	PatchRule(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)

	// (GET /users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id Id)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /executables)
func (_ Unimplemented) ListExecutables(w http.ResponseWriter, r *http.Request, params ListExecutablesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /executables/{id})
func (_ Unimplemented) GetExecutable(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /execution-events)
func (_ Unimplemented) ListExecutionEvents(w http.ResponseWriter, r *http.Request, params ListExecutionEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /execution-events/{id})
func (_ Unimplemented) DeleteExecutionEvent(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /execution-events/{id})
func (_ Unimplemented) GetExecutionEvent(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /file-access-events)
func (_ Unimplemented) ListFileAccessEvents(w http.ResponseWriter, r *http.Request, params ListFileAccessEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /file-access-events/{id})
func (_ Unimplemented) DeleteFileAccessEvent(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /file-access-events/{id})
func (_ Unimplemented) GetFileAccessEvent(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /group-memberships)
func (_ Unimplemented) ListGroupMemberships(w http.ResponseWriter, r *http.Request, params ListGroupMembershipsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /group-memberships)
func (_ Unimplemented) CreateGroupMembership(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /group-memberships/{id})
func (_ Unimplemented) DeleteGroupMembership(w http.ResponseWriter, r *http.Request, id GroupMembershipId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /group-memberships/{id})
func (_ Unimplemented) GetGroupMembership(w http.ResponseWriter, r *http.Request, id GroupMembershipId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /groups)
func (_ Unimplemented) ListGroups(w http.ResponseWriter, r *http.Request, params ListGroupsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /groups)
func (_ Unimplemented) CreateGroup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /groups/{id})
func (_ Unimplemented) DeleteGroup(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /groups/{id})
func (_ Unimplemented) GetGroup(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /groups/{id})
func (_ Unimplemented) PatchGroup(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /machines)
func (_ Unimplemented) ListMachines(w http.ResponseWriter, r *http.Request, params ListMachinesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /machines/{id})
func (_ Unimplemented) DeleteMachine(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /machines/{id})
func (_ Unimplemented) GetMachine(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /rule-targets)
func (_ Unimplemented) ListRuleTargets(w http.ResponseWriter, r *http.Request, params ListRuleTargetsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /rule-targets)
func (_ Unimplemented) CreateRuleTarget(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /rule-targets/{id})
func (_ Unimplemented) DeleteRuleTarget(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /rule-targets/{id})
func (_ Unimplemented) GetRuleTarget(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /rule-targets/{id})
func (_ Unimplemented) PatchRuleTarget(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /rules)
func (_ Unimplemented) ListRules(w http.ResponseWriter, r *http.Request, params ListRulesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /rules)
func (_ Unimplemented) CreateRule(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /rules/{id})
func (_ Unimplemented) DeleteRule(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /rules/{id})
func (_ Unimplemented) GetRule(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /rules/{id})
func (_ Unimplemented) PatchRule(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /users/{id})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListExecutables operation middleware
func (siw *ServerInterfaceWrapper) ListExecutables(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExecutablesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExecutables(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecutable operation middleware
func (siw *ServerInterfaceWrapper) GetExecutable(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecutable(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListExecutionEvents operation middleware
func (siw *ServerInterfaceWrapper) ListExecutionEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExecutionEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "machine_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "machine_id", r.URL.Query(), &params.MachineId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "machine_id", Err: err})
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", r.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// ------------- Optional query parameter "executable_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "executable_id", r.URL.Query(), &params.ExecutableId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "executable_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExecutionEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteExecutionEvent operation middleware
func (siw *ServerInterfaceWrapper) DeleteExecutionEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteExecutionEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecutionEvent operation middleware
func (siw *ServerInterfaceWrapper) GetExecutionEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecutionEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFileAccessEvents operation middleware
func (siw *ServerInterfaceWrapper) ListFileAccessEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFileAccessEventsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "machine_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "machine_id", r.URL.Query(), &params.MachineId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "machine_id", Err: err})
		return
	}

	// ------------- Optional query parameter "executable_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "executable_id", r.URL.Query(), &params.ExecutableId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "executable_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFileAccessEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFileAccessEvent operation middleware
func (siw *ServerInterfaceWrapper) DeleteFileAccessEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFileAccessEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFileAccessEvent operation middleware
func (siw *ServerInterfaceWrapper) GetFileAccessEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFileAccessEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGroupMemberships operation middleware
func (siw *ServerInterfaceWrapper) ListGroupMemberships(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupMembershipsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "group_id", r.URL.Query(), &params.GroupId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_id", Err: err})
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", r.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// ------------- Optional query parameter "machine_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "machine_id", r.URL.Query(), &params.MachineId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "machine_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroupMemberships(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGroupMembership operation middleware
func (siw *ServerInterfaceWrapper) CreateGroupMembership(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGroupMembership(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGroupMembership operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroupMembership(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GroupMembershipId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGroupMembership(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroupMembership operation middleware
func (siw *ServerInterfaceWrapper) GetGroupMembership(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id GroupMembershipId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroupMembership(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroups(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateGroup(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGroup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchGroup operation middleware
func (siw *ServerInterfaceWrapper) PatchGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMachines operation middleware
func (siw *ServerInterfaceWrapper) ListMachines(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMachinesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", r.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMachines(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMachine operation middleware
func (siw *ServerInterfaceWrapper) DeleteMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMachine(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMachine operation middleware
func (siw *ServerInterfaceWrapper) GetMachine(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMachine(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRuleTargets operation middleware
func (siw *ServerInterfaceWrapper) ListRuleTargets(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRuleTargetsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "rule_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "rule_id", r.URL.Query(), &params.RuleId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "rule_id", Err: err})
		return
	}

	// ------------- Optional query parameter "subject_kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "subject_kind", r.URL.Query(), &params.SubjectKind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subject_kind", Err: err})
		return
	}

	// ------------- Optional query parameter "subject_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "subject_id", r.URL.Query(), &params.SubjectId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subject_id", Err: err})
		return
	}

	// ------------- Optional query parameter "assignment" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "assignment", r.URL.Query(), &params.Assignment, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assignment", Err: err})
		return
	}

	// ------------- Optional query parameter "policy" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "policy", r.URL.Query(), &params.Policy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "policy", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRuleTargets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRuleTarget operation middleware
func (siw *ServerInterfaceWrapper) CreateRuleTarget(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRuleTarget(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRuleTarget operation middleware
func (siw *ServerInterfaceWrapper) DeleteRuleTarget(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRuleTarget(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRuleTarget operation middleware
func (siw *ServerInterfaceWrapper) GetRuleTarget(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRuleTarget(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchRuleTarget operation middleware
func (siw *ServerInterfaceWrapper) PatchRuleTarget(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchRuleTarget(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRules operation middleware
func (siw *ServerInterfaceWrapper) ListRules(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRulesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRules(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRule operation middleware
func (siw *ServerInterfaceWrapper) CreateRule(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRule operation middleware
func (siw *ServerInterfaceWrapper) DeleteRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRule operation middleware
func (siw *ServerInterfaceWrapper) GetRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchRule operation middleware
func (siw *ServerInterfaceWrapper) PatchRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchRule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/executables", wrapper.ListExecutables)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/executables/{id}", wrapper.GetExecutable)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/execution-events", wrapper.ListExecutionEvents)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/execution-events/{id}", wrapper.DeleteExecutionEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/execution-events/{id}", wrapper.GetExecutionEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/file-access-events", wrapper.ListFileAccessEvents)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/file-access-events/{id}", wrapper.DeleteFileAccessEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/file-access-events/{id}", wrapper.GetFileAccessEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/group-memberships", wrapper.ListGroupMemberships)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/group-memberships", wrapper.CreateGroupMembership)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/group-memberships/{id}", wrapper.DeleteGroupMembership)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/group-memberships/{id}", wrapper.GetGroupMembership)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/groups", wrapper.ListGroups)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/groups", wrapper.CreateGroup)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/groups/{id}", wrapper.DeleteGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/groups/{id}", wrapper.GetGroup)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/groups/{id}", wrapper.PatchGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/machines", wrapper.ListMachines)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/machines/{id}", wrapper.DeleteMachine)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/machines/{id}", wrapper.GetMachine)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rule-targets", wrapper.ListRuleTargets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/rule-targets", wrapper.CreateRuleTarget)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/rule-targets/{id}", wrapper.DeleteRuleTarget)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rule-targets/{id}", wrapper.GetRuleTarget)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/rule-targets/{id}", wrapper.PatchRuleTarget)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rules", wrapper.ListRules)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/rules", wrapper.CreateRule)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/rules/{id}", wrapper.DeleteRule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rules/{id}", wrapper.GetRule)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/rules/{id}", wrapper.PatchRule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}", wrapper.GetUser)
	})

	return r
}
