// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Cursor struct {
	MachineID       uuid.UUID          `json:"machine_id"`
	LastRuleCursor  pgtype.Text        `json:"last_rule_cursor"`
	LastEventCursor pgtype.Text        `json:"last_event_cursor"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID         int64              `json:"id"`
	MachineID  uuid.UUID          `json:"machine_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Kind       string             `json:"kind"`
	Payload    []byte             `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID          uuid.UUID          `json:"id"`
	DisplayName string             `json:"display_name"`
	Description pgtype.Text        `json:"description"`
	ObjectID    pgtype.Text        `json:"object_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GroupMember struct {
	GroupID   uuid.UUID          `json:"group_id"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Machine struct {
	ID                   uuid.UUID          `json:"id"`
	Serial               string             `json:"serial"`
	MachineIdentifier    string             `json:"machine_identifier"`
	Hostname             string             `json:"hostname"`
	UserID               pgtype.UUID        `json:"user_id"`
	ClientVersion        pgtype.Text        `json:"client_version"`
	ClientMode           string             `json:"client_mode"`
	PrimaryUser          pgtype.Text        `json:"primary_user"`
	CleanSyncRequested   bool               `json:"clean_sync_requested"`
	SyncCursor           pgtype.Text        `json:"sync_cursor"`
	RuleCursor           pgtype.Text        `json:"rule_cursor"`
	LastSeen             pgtype.Timestamptz `json:"last_seen"`
	LastPreflightAt      pgtype.Timestamptz `json:"last_preflight_at"`
	LastPostflightAt     pgtype.Timestamptz `json:"last_postflight_at"`
	LastRulesReceived    pgtype.Int4        `json:"last_rules_received"`
	LastRulesProcessed   pgtype.Int4        `json:"last_rules_processed"`
	LastPreflightPayload []byte             `json:"last_preflight_payload"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Rule struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Target    string             `json:"target"`
	Scope     string             `json:"scope"`
	Enabled   bool               `json:"enabled"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RuleAssignment struct {
	ID         int64              `json:"id"`
	RuleID     uuid.UUID          `json:"rule_id"`
	ScopeID    uuid.UUID          `json:"scope_id"`
	TargetType string             `json:"target_type"`
	Action     string             `json:"action"`
	UserID     pgtype.UUID        `json:"user_id"`
	GroupID    pgtype.UUID        `json:"group_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RuleScope struct {
	ID         uuid.UUID          `json:"id"`
	RuleID     uuid.UUID          `json:"rule_id"`
	TargetType string             `json:"target_type"`
	TargetID   uuid.UUID          `json:"target_id"`
	Action     string             `json:"action"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	Upn         string             `json:"upn"`
	DisplayName string             `json:"display_name"`
	ObjectID    pgtype.Text        `json:"object_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
